// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Error type for the `cargo-coverage-gate` library.
//!
//! Built on [`ohno`] for backtrace capture and error-chain support.
//! The library exposes a single [`CoverageGateError`] struct rather
//! than a typed-variant enum: callers propagate the error via
//! [`std::error::Error`] / [`Display`] or surface the message verbatim
//! through their own diagnostic surface. The kind of failure is
//! encoded in the message text and (where applicable) in the chained
//! source error.

/// An error returned from the `cargo-coverage-gate` library.
///
/// Carries a human-readable message and, when one exists, a chained
/// source error (typically the underlying `serde_json::Error` or
/// `cargo_metadata::Error`). The message rendered by [`Display`]
/// includes the chained source as `Caused by: …` automatically.
///
/// Construct via `CoverageGateError::new(message)` (no source) or
/// `CoverageGateError::caused_by(message, source)` (with source).
/// Both are generated by the `#[ohno::error]` attribute.
///
/// [`Display`]: std::fmt::Display
#[ohno::error]
#[display("{message}")]
pub struct CoverageGateError {
    message: String,
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use std::io;

    use super::*;

    #[test]
    fn new_carries_the_message() {
        let err = CoverageGateError::new("something broke".to_owned());
        assert!(err.to_string().contains("something broke"));
    }

    #[test]
    fn caused_by_chains_the_source() {
        let io_err = io::Error::new(io::ErrorKind::NotFound, "file gone");
        let err = CoverageGateError::caused_by("failed to read JSON".to_owned(), io_err);
        let rendered = err.to_string();
        assert!(rendered.contains("failed to read JSON"));
        assert!(rendered.contains("file gone"));
    }
}
