// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Repository-wide agent instructions shared by every backend.

use crate::catalog::Artifact;

const CARGO_ANVIL_INSTRUCTIONS: &str = include_str!("../../../templates/instructions/cargo-anvil.instructions.md");

/// `.github/instructions/cargo-anvil.instructions.md`.
#[must_use]
pub fn cargo_anvil() -> Artifact {
    Artifact::owned_file(".github/instructions/cargo-anvil.instructions.md", CARGO_ANVIL_INSTRUCTIONS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instructions_apply_to_the_whole_repository_and_explain_iteration() {
        assert_eq!(
            CARGO_ANVIL_INSTRUCTIONS.lines().take(3).collect::<Vec<_>>(),
            ["---", "applyTo: \"**\"", "---"]
        );
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY."));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-pr"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-setup"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-pr-fast"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-<check>"));
    }
}
