// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Repository-wide agent instructions shared by every backend.

use crate::catalog::Artifact;

const CARGO_ANVIL_INSTRUCTIONS: &str = include_str!("../../../templates/instructions/cargo-anvil.instructions.md");
const CARGO_ANVIL_ADOPTION_SKILL: &str = include_str!("../../../templates/skills/cargo-anvil-adoption/SKILL.md");

/// `.github/instructions/cargo-anvil.instructions.md`.
#[must_use]
pub fn cargo_anvil() -> Artifact {
    Artifact::owned_file(".github/instructions/cargo-anvil.instructions.md", CARGO_ANVIL_INSTRUCTIONS)
}

/// `.github/skills/cargo-anvil-adoption/SKILL.md`.
#[must_use]
pub fn adoption_skill() -> Artifact {
    Artifact::owned_file(".github/skills/cargo-anvil-adoption/SKILL.md", CARGO_ANVIL_ADOPTION_SKILL)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instructions_apply_to_the_whole_repository_and_explain_iteration() {
        assert_eq!(
            CARGO_ANVIL_INSTRUCTIONS.lines().take(3).collect::<Vec<_>>(),
            ["---", "applyTo: \"**\"", "---"]
        );
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY."));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-pr"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-setup"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-pr-fast"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just anvil-<check>"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("just` 1.46.0 or newer"));
        assert!(CARGO_ANVIL_INSTRUCTIONS.contains("In a local-only installation"));
    }

    #[test]
    fn adoption_skill_prefers_anvil_before_removing_duplicates() {
        assert_eq!(
            CARGO_ANVIL_ADOPTION_SKILL.lines().take(2).collect::<Vec<_>>(),
            ["---", "name: cargo-anvil-adoption"]
        );
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY."));
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("recommend the Anvil standard"));
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("Evaluate differences before deleting duplicates"));
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("solely to maintain exact legacy behavior"));
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("cargo anvil --dry-run"));
        assert!(CARGO_ANVIL_ADOPTION_SKILL.contains("local-only installation must run"));
    }
}
