// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! The generated `.anvil/*.just` recipe files and the `Justfile` import region.
//!
//! Source templates remain split by concern for maintainability. Their
//! top-level recipes become independently addressable delimiter-free catalog
//! sections; the engine composes them in catalog order into a small import hub,
//! checks file, and setup file. Container recipes compose separately.
//!
//! See [`local.md`](../../../docs/design/local.md) for the recipe surface.

use crate::catalog::Artifact;

/// Header and friendly alias that lead the composed Justfile.
const ENTRY_JUST: &str = include_str!("../../../templates/justfiles/anvil/entry.just");

const REPEATED_TEMPLATE_HEADER: &str = "# Copyright (c) Microsoft Corporation.\n\
# Licensed under the MIT License.\n\
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.\n\
# Update cargo-anvil and regenerate; repository-specific edits stop automatic updates.\n\
# Update behaviour: https://github.com/microsoft/ox-tools/blob/main/crates/cargo-anvil/docs/design/updates.md\n";

/// Repo-root-relative path of the generated import hub.
pub(crate) const ANVIL_JUST_PATH: &str = ".anvil/anvil.just";
/// Repo-root-relative path of check, group, tier, and impact recipes.
pub(crate) const CHECKS_JUST_PATH: &str = ".anvil/checks.just";
/// Repo-root-relative path of tool pins and setup/validation recipes.
pub(crate) const SETUP_JUST_PATH: &str = ".anvil/setup.just";

/// Contents of `justfiles/anvil/versions.just` baked into the binary.
const VERSIONS_JUST: &str = include_str!("../../../templates/justfiles/anvil/versions.just");

/// Contents of `justfiles/anvil/tools.just` baked into the binary.
const TOOLS_JUST: &str = include_str!("../../../templates/justfiles/anvil/tools.just");

/// Contents of `justfiles/anvil/helpers.just` baked into the binary.
/// Holds shared MSRV, cargo-mutants, and unscoped-tier helpers.
const HELPERS_JUST: &str = include_str!("../../../templates/justfiles/anvil/helpers.just");

/// Contents of `justfiles/anvil/impact.just` baked into the binary.
///
/// The single `anvil-impact` recipe and package-file selection expressions.
const IMPACT_JUST: &str = include_str!("../../../templates/justfiles/anvil/impact.just");

/// Emits `(path, include_str!)` pairs for a set of split recipe files that
/// live under a subdirectory of `justfiles/anvil/`. Each file is one owned
/// artifact, so the recipe tree is one file per check / per group rather
/// than a single monolithic `checks.just` / `groups.just`.
macro_rules! split_recipe_files {
    ($subdir:literal, [$($name:literal),* $(,)?]) => {
        &[$(
            (
                concat!("justfiles/anvil/", $subdir, "/", $name, ".just"),
                include_str!(concat!("../../../templates/justfiles/anvil/", $subdir, "/", $name, ".just")),
            ),
        )*]
    };
}

/// Generic local-development recipes that are not cloud check-group members.
const DEV_FILES: &[(&str, &str)] = split_recipe_files!("dev", ["build"]);

#[test]
fn aprz_delegates_github_cli_token_discovery_to_the_tool() {
    let aprz = CHECK_FILES
        .iter()
        .find_map(|(path, body)| path.ends_with("/aprz.just").then_some(*body))
        .expect("aprz.just is registered in CHECK_FILES below");
    assert!(aprz.contains("GITHUB_TOKEN"));
    assert!(aprz.contains("--github-token-from-gh"));
    assert!(!aprz.contains("gh auth token"));
}

/// One `justfiles/anvil/checks/<check>.just` file per catalog check
/// (the check recipe plus its paired `*-setup` / `*-validate-prereqs`).
const CHECK_FILES: &[(&str, &str)] = split_recipe_files!(
    "checks",
    [
        "aprz",
        "audit",
        "bench",
        "bolero",
        "careful",
        "cargo-hack",
        "cargo-sort",
        "clippy",
        "deny",
        "doc-build",
        "doc-test",
        "ensure-no-cyclic-deps",
        "ensure-no-default-features",
        "examples",
        "external-types",
        "fmt",
        "license-headers",
        "llvm-cov",
        "loom",
        "miri",
        "miri-race-coverage",
        "miri-strict-provenance",
        "miri-tree-borrows",
        "msrv-test",
        "mutants-diff",
        "mutants-full",
        "pr-title",
        "readme-check",
        "spellcheck",
        "udeps",
    ]
);

/// One `justfiles/anvil/groups/<group>.just` file per group (the group
/// recipe plus its paired `*-setup` / `*-validate-prereqs`).
const GROUP_FILES: &[(&str, &str)] = split_recipe_files!(
    "groups",
    [
        "pr-fast",
        "pr-msrv",
        "pr-slow",
        "pr-test",
        "pr-runtime-analysis",
        "pr-mutants",
        "scheduled-test",
        "scheduled-advisories",
        "scheduled-runtime-analysis",
        "scheduled-exhaustive",
    ]
);

/// Contents of `justfiles/anvil/tiers.just` baked into the binary.
const TIERS_JUST: &str = include_str!("../../../templates/justfiles/anvil/tiers.just");

/// Embedded body of the `anvil-imports` region in the user's Justfile.
pub(crate) const JUSTFILE_IMPORTS_BODY: &str = include_str!("../../../templates/regions/justfile-imports.just");

/// Region id for the imports block in the user's `Justfile`.
pub(crate) const JUSTFILE_REGION_ID: &str = "anvil-imports";

/// Canonical repo-root-relative path of the user's `Justfile`.
///
/// Capitalized to match the dominant Unix convention for repo-root
/// build-config files (`Makefile`, `Dockerfile`, `Rakefile`, ...). `just`
/// accepts either case, and the engine reuses whatever casing a repo already
/// has on disk.
pub(crate) const JUSTFILE_PATH: &str = "Justfile";

const JUSTFILE_SCAFFOLD: &str = "set unstable\n\
set windows-shell := [\"pwsh.exe\", \"-NoLogo\", \"-NoProfile\", \"-NonInteractive\", \"-Command\"]\n\n";

fn section(path: &'static str, id: impl Into<String>, body: impl Into<String>) -> Artifact {
    Artifact::owned_file_section(path, id, body.into().replace("\r\n", "\n"))
}

pub(crate) fn generated_header(path: &'static str, id: &'static str) -> Artifact {
    section(path, id, REPEATED_TEMPLATE_HEADER)
}

fn recipe_name(line: &str) -> Option<&str> {
    if line.is_empty() || line.len() != line.trim_start().len() || line.starts_with('#') || line.starts_with('[') || line.contains(":=") {
        return None;
    }
    let (head, _) = line.split_once(':')?;
    let name = head.split_whitespace().next()?;
    let generated_recipe_name =
        name.starts_with("anvil-") || name.starts_with("_anvil-") || name.starts_with("_install-") || name.starts_with("_check-");
    (generated_recipe_name && name.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))).then_some(name)
}

pub(crate) fn without_generated_header(body: &str) -> String {
    let normalized = body.replace("\r\n", "\n");
    normalized.strip_prefix(REPEATED_TEMPLATE_HEADER).unwrap_or(&normalized).to_owned()
}

pub(crate) fn template_sections(output_path: &'static str, source: &str, body: &str) -> Vec<Artifact> {
    let normalized = without_generated_header(body);
    let body = normalized.as_str();
    let lines = body.split_inclusive('\n').collect::<Vec<_>>();
    let recipe_headers = lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| recipe_name(line.trim_end_matches(['\r', '\n'])).map(|name| (index, name.to_owned())))
        .collect::<Vec<_>>();

    if recipe_headers.is_empty() {
        return vec![section(output_path, format!("source:{source}"), body)];
    }

    let mut starts = Vec::with_capacity(recipe_headers.len());
    for (header, name) in recipe_headers {
        let mut start = header;
        while start > 0 {
            let preceding = lines[start - 1].trim_end_matches(['\r', '\n']);
            if preceding.is_empty() || preceding.starts_with('#') || preceding.starts_with('[') {
                start -= 1;
            } else {
                break;
            }
        }
        starts.push((start, name));
    }

    let mut out = Vec::with_capacity(starts.len() + 1);
    if starts[0].0 > 0 {
        out.push(section(output_path, format!("source:{source}"), lines[..starts[0].0].concat()));
    }
    for (index, (start, name)) in starts.iter().enumerate() {
        let end = starts.get(index + 1).map_or(lines.len(), |(next, _)| *next);
        out.push(section(output_path, format!("recipe:{name}"), lines[*start..end].concat()));
    }
    out
}

fn is_setup_recipe(id: &str) -> bool {
    let Some(name) = id.strip_prefix("recipe:") else {
        return false;
    };
    name.ends_with("-setup")
        || name.ends_with("-validate-prereqs")
        || name.starts_with("anvil-tool-")
        || name.starts_with("anvil-component-")
        || name.starts_with("anvil-toolchain-")
        || name.starts_with("_install-")
        || name.starts_with("_check-")
        || name == "_anvil-root-msrv"
}

fn route_setup_sections(sections: &mut [Artifact]) {
    for artifact in sections {
        let Artifact::OwnedFileSection(spec) = artifact else {
            continue;
        };
        if is_setup_recipe(&spec.id) {
            spec.path = SETUP_JUST_PATH;
        }
    }
}

fn check_template_sections(source: &str, body: &str) -> Vec<Artifact> {
    let mut sections = template_sections(CHECKS_JUST_PATH, source, body);
    route_setup_sections(&mut sections);
    sections
}

/// Header and `anvil` alias for the composed recipe file.
#[must_use]
pub fn entry() -> Artifact {
    section(ANVIL_JUST_PATH, "alias:anvil", ENTRY_JUST)
}

/// Generated-content headers for the non-container composed recipe files.
#[must_use]
pub fn headers() -> Vec<Artifact> {
    vec![
        generated_header(CHECKS_JUST_PATH, "header:checks"),
        generated_header(SETUP_JUST_PATH, "header:setup"),
    ]
}

/// One-time scaffold for a repository that has no root Justfile yet.
#[must_use]
pub(crate) const fn scaffold() -> &'static str {
    JUSTFILE_SCAFFOLD
}

/// Pinned toolchain and cargo-subcommand version declarations.
#[must_use]
pub fn versions() -> Vec<Artifact> {
    template_sections(SETUP_JUST_PATH, "versions", VERSIONS_JUST)
}

/// Tool install and prerequisite recipes.
#[must_use]
pub fn tools() -> Vec<Artifact> {
    template_sections(SETUP_JUST_PATH, "tools", TOOLS_JUST)
}

/// Shared helper recipes and impact contract.
#[must_use]
pub fn helpers() -> Vec<Artifact> {
    check_template_sections("helpers", HELPERS_JUST)
}

/// Shared `anvil-impact` recipe.
#[must_use]
pub fn impact() -> Vec<Artifact> {
    check_template_sections("impact", IMPACT_JUST)
}

/// Generic local-development recipe files.
#[must_use]
pub fn dev_files() -> Vec<Artifact> {
    DEV_FILES
        .iter()
        .flat_map(|&(path, body)| check_template_sections(path, body))
        .collect()
}

/// The `justfiles/anvil/checks/<check>.just` files — one owned artifact
/// per catalog check.
#[must_use]
pub fn check_files() -> Vec<Artifact> {
    CHECK_FILES
        .iter()
        .flat_map(|&(path, body)| check_template_sections(path, body))
        .collect()
}

/// The `justfiles/anvil/groups/<group>.just` files — one owned artifact
/// per group.
#[must_use]
pub fn group_files() -> Vec<Artifact> {
    GROUP_FILES
        .iter()
        .flat_map(|&(path, body)| check_template_sections(path, body))
        .collect()
}

/// `justfiles/anvil/tiers.just` — the tier aggregators.
#[must_use]
pub fn tiers() -> Vec<Artifact> {
    check_template_sections("tiers", TIERS_JUST)
}

/// Look up one built-in Just recipe by its top-level name.
///
/// This is the preferred entry point for a derived catalog that wants to
/// replace or remove one recipe without taking ownership of neighboring
/// declarations in the source template.
#[must_use]
pub fn recipe(name: &str) -> Option<Artifact> {
    let id = format!("recipe:{name}");
    tools()
        .into_iter()
        .chain(versions())
        .chain(helpers())
        .chain(impact())
        .chain(tiers())
        .chain(dev_files())
        .chain(check_files())
        .chain(group_files())
        .find(|artifact| {
            matches!(
                artifact,
                Artifact::OwnedFileSection(section) if section.id == id
            )
        })
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};
    use std::process::Command;

    use ImpactPolicy::{Affected, Modified, Required, Unscoped};
    use tempfile::TempDir;

    use super::*;
    use crate::Catalog;

    /// A check's impact-scoping policy: either unscoped (always runs the full
    /// workspace) or scoped to one cargo-delta impact category.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum ImpactPolicy {
        Unscoped,
        Modified,
        Affected,
        Required,
    }

    impl ImpactPolicy {
        /// The cargo-delta package-file category this policy consumes, or
        /// `None` when the check is unscoped.
        fn category(self) -> Option<&'static str> {
            match self {
                Self::Unscoped => None,
                Self::Modified => Some("modified"),
                Self::Affected => Some("affected"),
                Self::Required => Some("required"),
            }
        }
    }

    /// The intended impact policy for every catalog check -- the canonical
    /// mapping `every_check_matches_its_declared_impact_policy` enforces
    /// against the emitted recipes. Keep in sync with the check mapping table
    /// in the design docs.
    const EXPECTED_CHECK_POLICY: &[(&str, ImpactPolicy)] = {
        &[
            ("aprz", Unscoped),
            ("audit", Unscoped),
            ("bench", Affected),
            ("bolero", Affected),
            ("careful", Affected),
            ("cargo-hack", Required),
            ("cargo-sort", Modified),
            ("clippy", Affected),
            ("deny", Unscoped),
            ("doc-build", Required),
            ("doc-test", Affected),
            ("ensure-no-cyclic-deps", Modified),
            ("ensure-no-default-features", Modified),
            ("examples", Affected),
            ("external-types", Affected),
            ("fmt", Modified),
            ("license-headers", Modified),
            ("llvm-cov", Affected),
            ("loom", Affected),
            ("miri", Affected),
            ("miri-race-coverage", Affected),
            ("miri-strict-provenance", Affected),
            ("miri-tree-borrows", Affected),
            ("msrv-test", Affected),
            ("mutants-diff", Affected),
            ("mutants-full", Unscoped),
            ("pr-title", Unscoped),
            // readme-check + spellcheck are unscoped: their inputs (workspace
            // README template, root .spelling dictionary) are repo-level files
            // cargo-delta does not map to a package, so scoping them would
            // silently skip a changed template/dictionary.
            ("readme-check", Unscoped),
            ("spellcheck", Unscoped),
            ("udeps", Required),
        ]
    };

    #[test]
    fn tools_just_template_is_not_empty() {
        assert!(TOOLS_JUST.contains("installed_cargo_tools := `cargo install --list`"));
        assert!(TOOLS_JUST.contains("anvil-tool-cargo-deny-install"));
        assert!(TOOLS_JUST.contains("anvil-tool-cargo-deny-validate-prereqs"));
        assert!(TOOLS_JUST.contains("anvil-component-default-clippy-install"));
        assert!(TOOLS_JUST.contains("anvil-toolchain-stable-install"));
        assert!(TOOLS_JUST.contains("anvil-toolchain-nightly-install"));
    }

    #[cfg_attr(miri, ignore = "spawns just; miri isolation forbids it")]
    #[test]
    fn composed_justfile_parses() {
        let mut files = BTreeMap::<&str, String>::new();
        for artifact in Catalog::anvil().artifacts() {
            let Artifact::OwnedFileSection(section) = artifact else {
                continue;
            };
            if !std::path::Path::new(section.path)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("just"))
            {
                continue;
            }
            let body = files.entry(section.path).or_default();
            if !body.is_empty() {
                body.push_str("\n\n");
            }
            body.push_str(section.body.trim_matches(['\r', '\n']));
            body.push('\n');
        }
        assert_eq!(
            files
                .values()
                .map(|body| body.matches("GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.").count())
                .sum::<usize>(),
            4,
            "each generated recipe file must carry one generated-content header"
        );
        let temp = TempDir::new().expect("temporary Justfile directory must be creatable");
        for (relative, body) in files {
            let path = temp.path().join(relative);
            std::fs::create_dir_all(path.parent().expect("generated recipe path has a parent"))
                .expect("generated recipe directory must be creatable");
            std::fs::write(path, body).expect("composed Justfile fixture must be writable");
        }
        let root = temp.path().join("Justfile");
        std::fs::write(
            &root,
            "set unstable\nset windows-shell := [\"pwsh\", \"-NoProfile\", \"-Command\"]\nimport '.anvil/anvil.just'\n",
        )
        .expect("root Justfile fixture must be writable");

        let output = Command::new("just")
            .args(["--justfile"])
            .arg(&root)
            .arg("--dump")
            .output()
            .expect("just must be available for generated-recipe tests");
        assert!(
            output.status.success(),
            "composed Justfile did not parse:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn recipes_are_independently_addressable_catalog_sections() {
        let recipe = recipe("anvil-clippy").expect("the built-in clippy recipe must be addressable");
        let Artifact::OwnedFileSection(section) = recipe else {
            panic!("a Just recipe must be an owned-file section");
        };
        assert_eq!(section.path, CHECKS_JUST_PATH);
        assert_eq!(section.id, "recipe:anvil-clippy");
        assert!(section.body.contains("anvil-clippy:"));
        assert!(!section.body.contains("anvil-clippy-setup"));
    }

    #[test]
    fn recipe_section_ids_are_unique() {
        let mut ids = BTreeSet::new();
        for artifact in tools()
            .into_iter()
            .chain(versions())
            .chain(helpers())
            .chain(impact())
            .chain(tiers())
            .chain(dev_files())
            .chain(check_files())
            .chain(group_files())
        {
            let Artifact::OwnedFileSection(section) = artifact else {
                continue;
            };
            assert!(ids.insert(section.id.clone()), "duplicate Just section id: {}", section.id);
        }
    }

    #[test]
    fn shared_assignments_live_in_the_tools_preamble() {
        let preamble = tools()
            .into_iter()
            .find(|artifact| {
                matches!(
                    artifact,
                    Artifact::OwnedFileSection(section) if section.id == "source:tools"
                )
            })
            .expect("tools preamble must be independently addressable");
        assert!(preamble.body().contains("bolero_command_prefix :="));
        assert!(preamble.body().contains("mutants_command_prefix :="));
        assert!(
            !recipe("anvil-tool-cargo-audit-validate-prereqs")
                .unwrap()
                .body()
                .contains("bolero_command_prefix :=")
        );
        assert!(
            !recipe("anvil-tool-cargo-llvm-cov-validate-prereqs")
                .unwrap()
                .body()
                .contains("mutants_command_prefix :=")
        );
    }

    /// All `checks/*.just` bodies concatenated, for content assertions.
    fn all_check_bodies() -> String {
        CHECK_FILES.iter().map(|(_, b)| *b).collect::<Vec<_>>().join("\n")
    }

    /// All `groups/*.just` bodies concatenated, for content assertions.
    fn all_group_bodies() -> String {
        GROUP_FILES.iter().map(|(_, b)| *b).collect::<Vec<_>>().join("\n")
    }

    fn defines_recipe(body: &str, recipe: &str) -> bool {
        body.lines().any(|line| {
            line.strip_prefix(recipe)
                .is_some_and(|suffix| suffix.starts_with(':') || suffix.starts_with(' '))
        })
    }

    #[test]
    fn checks_just_template_includes_all_catalog_checks() {
        let checks = all_check_bodies();
        for needle in [
            "anvil-fmt",
            "anvil-clippy",
            "anvil-license-headers",
            "anvil-pr-title",
            "anvil-llvm-cov",
            "anvil-doc-test",
            "anvil-mutants-diff",
            "anvil-miri",
            "anvil-mutants-full",
            "anvil-bench",
        ] {
            assert!(defines_recipe(&checks, needle), "checks tree missing recipe '{needle}'");
        }
    }

    #[test]
    fn checks_fail_closed_and_preserve_opted_out_tests() {
        let checks = all_check_bodies();
        for needle in [
            "anvil-bolero: target discovery failed",
            "${prefix}: cargo metadata failed",
            "coverage-gate '{packages}' run",
            "could not resolve the cargo-careful executable",
            "mutants_command_prefix",
        ] {
            assert!(checks.contains(needle), "checks tree missing safety behavior '{needle}'");
        }
        assert!(
            checks.contains("bolero list --profile release --package '{name}'"),
            "bolero discovery must use the execution profile through cargo-each"
        );
        assert!(
            checks.contains("bolero test --profile release --engine libfuzzer"),
            "bolero execution must use the profile option accepted by the pinned cargo-bolero"
        );
        assert!(
            !checks.contains("bolero list @bareArgs"),
            "bolero discovery must not pass repeated --package arguments"
        );
        assert!(!checks.contains("bolero list failed; assuming no targets"));
    }

    #[test]
    fn installers_are_portable_and_binstall_can_compile_as_a_fallback() {
        assert!(
            TOOLS_JUST.contains("installed_cargo_tools := `cargo install --list`"),
            "tool inventory must be a lazy direct Cargo invocation"
        );
        assert!(
            TOOLS_JUST.contains("semver_matches(installed, \">=\" + minimum)"),
            "validation must accept equal or newer tool versions"
        );
        assert!(
            TOOLS_JUST.contains("binstall --no-confirm --locked --version ="),
            "binstall mode must remain one portable domain-tool invocation"
        );
        assert!(
            !TOOLS_JUST.contains("--disable-strategies compile"),
            "binstall mode must remain usable before binary indexes contain a newly published tool"
        );
    }

    #[test]
    fn each_check_file_defines_its_own_check_recipe() {
        // The file `checks/<name>.just` must define `anvil-<name>` -- guards
        // against a mis-split that files a check's recipe under the wrong name.
        for (path, body) in CHECK_FILES {
            let stem = path
                .strip_prefix("justfiles/anvil/checks/")
                .and_then(|p| p.strip_suffix(".just"))
                .expect("check file path has the expected shape");
            let recipe = format!("anvil-{stem}");
            assert!(defines_recipe(body, &recipe), "{path} must define '{recipe}'");
        }
    }

    #[test]
    fn impact_scoped_checks_consume_package_files_through_cargo_each() {
        let mut scoped = 0;
        for (path, body) in CHECK_FILES {
            for category in ["modified", "affected", "required"] {
                if !body.contains(&format!("anvil_{category}_selection")) {
                    continue;
                }
                scoped += 1;
                assert!(
                    body.contains(" each "),
                    "{path} must delegate package-file consumption to cargo-each"
                );
            }
        }
        assert!(scoped >= 15, "the impact-scoped check set unexpectedly collapsed");
    }

    #[test]
    fn miri_profiles_inherit_the_cargo_each_runner() {
        let miri = CHECK_FILES
            .iter()
            .find_map(|(path, body)| path.ends_with("/miri.just").then_some(*body))
            .expect("miri.just is registered in CHECK_FILES");
        for needle in [
            "_anvil-miri-test profile package=\"\" test_filter=\"\" example=\"\": anvil-impact",
            "cargo '+{{ rust_nightly }}' each",
            "--exclude-filter 'metadata:anvil.miri.exclude=true'",
            "--jobs {{ anvil_miri_jobs }}",
            "--keep-going",
            "miri test --package '{spec}'",
        ] {
            assert!(miri.contains(needle), "miri runner is missing '{needle}'");
        }

        for (check, profile) in [
            ("miri", "standard"),
            ("miri-tree-borrows", "tree-borrows"),
            ("miri-strict-provenance", "strict-provenance"),
            ("miri-race-coverage", "race-coverage"),
        ] {
            let body = CHECK_FILES
                .iter()
                .find_map(|(path, body)| path.ends_with(&format!("/{check}.just")).then_some(*body))
                .unwrap_or_else(|| panic!("{check}.just is registered in CHECK_FILES"));
            let dependency = if check == "miri" {
                format!("(_anvil-miri-test \"{profile}\" package test example)")
            } else {
                format!("(_anvil-miri-test \"{profile}\")")
            };
            assert!(
                body.contains(&dependency),
                "{check}.just must inherit the shared Miri executable runner with its profile"
            );
            assert!(
                !body.contains("& \"{{ just_executable() }}\" _anvil-miri-test"),
                "{check}.just must not launch the main Miri runner through a nested just process"
            );
        }
    }

    #[test]
    fn impact_recipe_writes_direct_package_file_artifacts() {
        assert!(IMPACT_JUST.contains("anvil-impact:"));
        for tier in ["modified", "affected", "required"] {
            assert!(IMPACT_JUST.contains(&format!("--{tier} --format packages")));
            assert!(IMPACT_JUST.contains(&format!("target/anvil/impact/{tier}.packages")));
            assert!(IMPACT_JUST.contains(&format!("anvil_{tier}_selection")));
        }
        assert!(!IMPACT_JUST.contains("ConvertFrom-Json"));
        assert!(!IMPACT_JUST.contains("_anvil-impact-format"));
    }

    #[test]
    fn every_check_matches_its_declared_impact_policy() {
        // Single source of truth for each check's impact policy. The catalog
        // encodes the policy structurally -- an `_anvil-impact-include
        // <category>` call, or its absence for unscoped checks -- and this
        // table pins the intended value. Pinning the exact category per check
        // (rather than a bare count) makes a check silently changing category,
        // or gaining/losing scoping, fail here instead of slipping through.
        let expected: BTreeMap<&str, ImpactPolicy> = EXPECTED_CHECK_POLICY.iter().copied().collect();
        assert_eq!(
            expected.len(),
            EXPECTED_CHECK_POLICY.len(),
            "EXPECTED_CHECK_POLICY contains a duplicate check entry"
        );
        let miri_runner = CHECK_FILES
            .iter()
            .find_map(|(path, body)| path.ends_with("/miri.just").then_some(*body))
            .expect("miri.just is registered in CHECK_FILES");

        let mut seen = BTreeSet::new();
        for (path, body) in CHECK_FILES {
            let stem = path
                .strip_prefix("justfiles/anvil/checks/")
                .and_then(|p| p.strip_suffix(".just"))
                .expect("check file path has the expected shape");
            seen.insert(stem);
            let policy = *expected
                .get(stem)
                .unwrap_or_else(|| panic!("check '{stem}' is missing from EXPECTED_CHECK_POLICY; classify it explicitly"));
            let execution_body = if body.contains("(_anvil-miri-test \"") { miri_runner } else { body };

            // Parse the package-file selector used by the recipe.
            let calls: Vec<&str> = ["modified", "affected", "required"]
                .into_iter()
                .filter(|cat| {
                    execution_body.contains(&format!("anvil_{cat}_selection")) || execution_body.contains(&format!("{cat}.packages"))
                })
                .collect();
            assert!(
                calls.len() <= 1,
                "{path} makes contradictory impact-include calls {calls:?}; a check resolves exactly one category"
            );
            let depends_on_impact = execution_body
                .lines()
                .filter(|line| !line.starts_with('#') && !line.chars().next().is_some_and(char::is_whitespace))
                .filter_map(|line| line.split_once(':'))
                .any(|(_, dependencies)| dependencies.split_whitespace().any(|dependency| dependency == "anvil-impact"));

            match policy.category() {
                None => {
                    // Unscoped: no cache dependency, no include call.
                    assert!(calls.is_empty(), "{path} is declared Unscoped but consumes an impact selection");
                    assert!(!depends_on_impact, "{path} is declared Unscoped but depends on anvil-impact");
                }
                Some(category) => {
                    assert_eq!(
                        calls.as_slice(),
                        &[category],
                        "{path}: declared {policy:?} but its package-file selection is {calls:?}"
                    );
                    // A scoped check must depend on anvil-impact so the package
                    // file is fresh and delegate its consumption to cargo-each.
                    assert!(
                        depends_on_impact,
                        "{path} reads the impact cache but does not depend on anvil-impact"
                    );
                    assert!(
                        execution_body.contains(" each "),
                        "{path} must delegate the selection to cargo-each"
                    );
                }
            }
            assert!(
                !body.contains("ANVIL_INCLUDE_"),
                "{path} must not reference the removed ANVIL_INCLUDE_* env vars"
            );
        }

        // Bijection: every declared check exists as a file, and every file is
        // declared -- so adding or removing a check forces an explicit policy.
        let declared: BTreeSet<&str> = expected.keys().copied().collect();
        assert_eq!(
            declared, seen,
            "EXPECTED_CHECK_POLICY and the check catalog disagree on the set of checks"
        );

        // Guard the headline scoped/unscoped split so a wholesale policy shift
        // is a deliberate, reviewed edit rather than an accident.
        let scoped = EXPECTED_CHECK_POLICY.iter().filter(|(_, p)| p.category().is_some()).count();
        let unscoped = EXPECTED_CHECK_POLICY.len() - scoped;
        assert_eq!(
            (scoped, unscoped),
            (23, 7),
            "impact scoped/unscoped split changed; update EXPECTED_CHECK_POLICY deliberately"
        );
    }

    #[test]
    fn groups_just_template_includes_all_groups_and_pr_slow_groups() {
        let groups = all_group_bodies();
        for needle in [
            "anvil-pr-fast:",
            "anvil-pr-slow:",
            "anvil-pr-test:",
            "anvil-pr-msrv:",
            "anvil-pr-runtime-analysis:",
            "anvil-pr-mutants:",
            "anvil-scheduled-test:",
            "anvil-scheduled-advisories:",
            "anvil-scheduled-exhaustive:",
        ] {
            assert!(groups.contains(needle), "groups tree missing '{needle}'");
        }
        for needle in ["anvil-pr-slow1:", "anvil-pr-slow2:", "anvil-pr-slow3:"] {
            assert!(!groups.contains(needle), "groups tree still contains stale '{needle}'");
        }
        assert!(groups.contains(
            "anvil-pr-slow: anvil-pr-slow-validate-prereqs anvil-pr-test anvil-pr-msrv anvil-pr-runtime-analysis anvil-pr-mutants"
        ));
        // PR group recipes list their own validate-prereqs aggregate first so
        // all tool checks run up front (just dedups the per-check ones).
        for needle in [
            "anvil-pr-fast: anvil-pr-fast-validate-prereqs",
            "anvil-pr-test: anvil-pr-test-validate-prereqs",
            "anvil-pr-msrv: anvil-pr-msrv-validate-prereqs",
            "anvil-pr-runtime-analysis: anvil-pr-runtime-analysis-validate-prereqs",
            "anvil-pr-mutants: anvil-pr-mutants-validate-prereqs",
        ] {
            assert!(
                groups.contains(needle),
                "group recipe must run its validate-prereqs first: '{needle}'"
            );
        }
        // Scheduled groups are the full-workspace backstop: the public recipe
        // wraps in `_anvil-unscoped` (forcing ANVIL_IMPACT=off before the deps
        // run), and the private `_anvil-<group>` fan-out lists its
        // validate-prereqs aggregate first.
        for g in [
            "scheduled-test",
            "scheduled-advisories",
            "scheduled-runtime-analysis",
            "scheduled-exhaustive",
        ] {
            assert!(
                groups.contains(&format!("anvil-{g}: (_anvil-unscoped \"{g}\")")),
                "scheduled group {g} must wrap in _anvil-unscoped"
            );
            assert!(
                groups.contains(&format!("_anvil-{g}: anvil-{g}-validate-prereqs")),
                "scheduled group {g} private fan-out must run its validate-prereqs first"
            );
        }
    }

    #[test]
    fn impact_scoped_groups_declare_cargo_delta_prereq() {
        // Every PR group whose checks are impact-scoped depends (transitively,
        // via each scoped check) on `anvil-impact`, which invokes cargo-delta
        // when it (re)computes the impact set. The group's setup +
        // validate-prereqs must therefore install / verify cargo-delta, so a
        // missing tool fails fast at setup rather than mid-run. (pr-slow is an
        // umbrella and inherits this via pr-test / pr-msrv /
        // pr-runtime-analysis / pr-mutants.) Scheduled groups force
        // ANVIL_IMPACT=off and never
        // recompute the impact set, so they deliberately do NOT depend on
        // cargo-delta.
        let groups = all_group_bodies();
        for g in ["pr-fast", "pr-test", "pr-msrv", "pr-runtime-analysis", "pr-mutants"] {
            assert!(
                groups.contains(&format!(
                    "anvil-{g}-setup installer=\"install\": \\\n    (anvil-tool-cargo-delta-install installer)"
                )),
                "group {g} setup must install cargo-delta"
            );
            assert!(
                groups.contains(&format!(
                    "anvil-{g}-validate-prereqs: \\\n    anvil-tool-cargo-delta-validate-prereqs"
                )),
                "group {g} validate-prereqs must verify cargo-delta"
            );
        }
        // Scheduled groups force impact off and never recompute, so they must
        // NOT carry cargo-delta as a prerequisite.
        for g in [
            "scheduled-test",
            "scheduled-advisories",
            "scheduled-runtime-analysis",
            "scheduled-exhaustive",
        ] {
            assert!(
                !groups.contains(&format!(
                    "anvil-{g}-setup installer=\"install\": \\\n    (anvil-tool-cargo-delta-install installer)"
                )),
                "scheduled group {g} must not install cargo-delta (it forces ANVIL_IMPACT=off and never recomputes)"
            );
            assert!(
                !groups.contains(&format!(
                    "anvil-{g}-validate-prereqs: \\\n    anvil-tool-cargo-delta-validate-prereqs"
                )),
                "scheduled group {g} must not verify cargo-delta (it forces ANVIL_IMPACT=off and never recomputes)"
            );
        }
    }

    #[test]
    fn tiers_just_template_has_three_tiers() {
        for needle in ["anvil-pr:", "anvil-scheduled:", "anvil-full:", "_anvil-scheduled:", "_anvil-full:"] {
            assert!(TIERS_JUST.contains(needle), "tiers.just missing '{needle}'");
        }
        // Containerized execution is reached only through the explicit
        // `anvil-container` recipe, so no tier routes through a native/container
        // seam. The PR tier depends on its work directly. The scheduled and full
        // tiers are the full-workspace backstop for PR-tier impact scoping, so
        // they wrap a private `_anvil-<tier>` recipe that carries the
        // validate-prereqs aggregate (run first, so a missing tool fails up
        // front) and inherits ANVIL_IMPACT=off from the wrapper.
        assert!(!TIERS_JUST.contains("_anvil-run"), "tiers must not route through an execution seam");
        for needle in [
            "anvil-pr: anvil-pr-validate-prereqs",
            "anvil-scheduled: (_anvil-unscoped \"scheduled\")",
            "_anvil-scheduled: anvil-scheduled-validate-prereqs",
            "anvil-full: (_anvil-unscoped \"full\")",
            "_anvil-full: anvil-full-validate-prereqs",
        ] {
            assert!(TIERS_JUST.contains(needle), "tier wrapper missing '{needle}'");
        }
        // Scoping is disabled by a parent process, because `just` runs each
        // dependency as its own process and a dependency-only recipe's body
        // executes after its dependencies.
        assert!(
            HELPERS_JUST.contains("$env:ANVIL_IMPACT = 'off'"),
            "the wrapper must force ANVIL_IMPACT=off for the scheduled/full tiers"
        );
        // The scheduled tier must fan out to every scheduled group, including
        // runtime-analysis (a separate group from exhaustive).
        for needle in [
            "anvil-scheduled-test",
            "anvil-scheduled-advisories",
            "anvil-scheduled-runtime-analysis",
            "anvil-scheduled-exhaustive",
        ] {
            assert!(TIERS_JUST.contains(needle), "scheduled tier must reference group '{needle}'");
        }
        // The catch-all `anvil-setup` / `anvil-validate-prereqs` must also
        // install / verify cargo-delta (the impact tool), so a local
        // `just anvil-setup` provisions a complete environment even though
        // cargo-delta isn't wired into any per-group setup.
        assert!(
            TIERS_JUST
                .contains("anvil-setup installer=\"install\": (anvil-full-setup installer) (anvil-tool-cargo-delta-install installer)"),
            "anvil-setup must install cargo-delta"
        );
        assert!(
            TIERS_JUST.contains("anvil-validate-prereqs: anvil-full-validate-prereqs anvil-tool-cargo-delta-validate-prereqs"),
            "anvil-validate-prereqs must verify cargo-delta"
        );
    }

    #[test]
    fn versions_just_has_known_tools() {
        for needle in [
            "cargo_nextest_version",
            "cargo_llvm_cov_version",
            "cargo_deny_version",
            "cargo_each_version",
            "cargo_mutants_version",
        ] {
            assert!(VERSIONS_JUST.contains(needle), "versions.just missing variable '{needle}'");
        }
    }

    #[test]
    fn stable_toolchain_selection_is_scoped_to_each_command() {
        assert!(!VERSIONS_JUST.contains("export RUSTUP_TOOLCHAIN"));
        assert!(IMPACT_JUST.contains("anvil_stable_toolchain_arg :="));
        assert!(IMPACT_JUST.contains("+{workspace-rust-version}"));
        assert!(!TOOLS_JUST.contains("_anvil-resolve-stable"));
        assert!(!TOOLS_JUST.contains("[script(\"pwsh\""));
        assert!(TOOLS_JUST.contains("cargo each --workspace --once -- cargo "));
        assert!(TOOLS_JUST.contains("rustup component add --toolchain"));
        assert!(!TOOLS_JUST.contains("rustup target add --toolchain"));
    }

    #[test]
    fn setup_graph_owns_stable_toolchain_provisioning() {
        assert!(
            TOOLS_JUST.contains("anvil-toolchain-stable-install installer=\"install\": (anvil-tool-cargo-each-install installer)"),
            "cargo-each must bootstrap stable provisioning"
        );
        assert!(
            TOOLS_JUST.contains("cargo each --workspace --once -- rustup toolchain install '{workspace-rust-version}'"),
            "stable fallback must delegate workspace rust-version resolution to cargo-each"
        );
        assert!(
            TOOLS_JUST.contains("bolero_command_prefix"),
            "Bolero's platform gate must be a Just-time condition"
        );
        assert!(
            TOOLS_JUST.contains("mutants_command_prefix"),
            "cargo-mutants' platform gate must be a Just-time condition"
        );
        for component in ["clippy", "rustfmt"] {
            let expected =
                format!("anvil-component-default-{component}-install installer=\"install\": (anvil-toolchain-stable-install installer)");
            assert!(
                TOOLS_JUST.contains(&expected),
                "default component '{component}' must provision stable first"
            );
        }
        let checks = all_check_bodies();
        for check in ["bench", "doc-build", "doc-test", "examples", "loom"] {
            let setup = format!("anvil-{check}-setup installer=\"install\": (anvil-toolchain-stable-install installer)");
            let validation = format!("anvil-{check}-validate-prereqs: anvil-tool-rustc-validate-prereqs");
            assert!(checks.contains(&setup), "{check} setup must provision stable");
            assert!(
                checks.contains(&validation),
                "{check} validation must remain read-only prerequisite validation"
            );
        }
        assert!(
            !checks.contains("validate-prereqs: anvil-toolchain-stable-install"),
            "validate-prereqs recipes must never install stable"
        );
        assert!(TOOLS_JUST.contains("semver_matches(installed, \">=\" + minimum)"));

        let groups = all_group_bodies();
        assert!(
            groups.contains("(anvil-tool-cargo-delta-install installer)") && groups.contains("(anvil-bench-setup installer)"),
            "representative group setup paths must reach stable provisioning through Cargo-tool or stable-only leaf setup"
        );
        assert!(
            TIERS_JUST.contains("anvil-full-setup installer=\"install\":")
                && TIERS_JUST.contains("(anvil-pr-setup installer)")
                && TIERS_JUST.contains("anvil-setup installer=\"install\": (anvil-full-setup installer)"),
            "full and global setup must retain their transitive path to stable provisioning"
        );
    }

    #[test]
    fn checks_use_portable_stable_toolchain_selection() {
        let checks = all_check_bodies();
        assert!(checks.contains("anvil_stable_toolchain_arg"));
        assert!(!checks.contains("_anvil_stable_toolchain_args"));
    }

    #[test]
    fn entry_section_imports_generated_recipe_files_and_defines_alias() {
        assert!(ENTRY_JUST.contains("alias anvil := anvil-pr"));
        for import in ["setup.just", "checks.just", "container.just"] {
            assert!(ENTRY_JUST.contains(&format!("import '{import}'")));
        }
    }

    #[test]
    fn versions_just_defines_both_nightly_pins() {
        assert!(VERSIONS_JUST.contains("rust_nightly :="), "versions.just missing rust_nightly");
        assert!(
            VERSIONS_JUST.contains("rust_nightly_external_types :="),
            "versions.just missing rust_nightly_external_types"
        );
    }

    #[test]
    fn checks_just_has_no_floating_nightly_invocations() {
        let checks = all_check_bodies();
        for line in checks.lines() {
            let stripped = line.split('#').next().unwrap_or("");
            assert!(
                !stripped.contains("+nightly "),
                "checks tree has a floating '+nightly' invocation: {line}"
            );
            assert!(
                !stripped.contains("'+nightly'"),
                "checks tree has a floating '+nightly' invocation: {line}"
            );
        }
    }

    #[test]
    fn justfile_imports_body_is_a_single_import_line() {
        let body = JUSTFILE_IMPORTS_BODY.trim();
        assert_eq!(body, "import '.anvil/anvil.just'");
    }
}
