// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! The composed `.anvil/anvil.just` recipe file and the `Justfile` import region.
//!
//! Source templates remain split by concern for maintainability. Their
//! top-level recipes become independently addressable delimiter-free catalog
//! sections; the engine composes them in catalog order into one fully owned
//! physical file.
//!
//! See [`local.md`](../../../docs/design/local.md) for the recipe surface.

use crate::catalog::Artifact;

/// Header and friendly alias that lead the composed Justfile.
const ENTRY_JUST: &str = include_str!("../../../templates/justfiles/anvil/entry.just");

const REPEATED_TEMPLATE_HEADER: &str = "# Copyright (c) Microsoft Corporation.\n\
# Licensed under the MIT License.\n\
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.\n\
# Update cargo-anvil and regenerate; repository-specific edits stop automatic updates.\n\
# Update behaviour: https://github.com/microsoft/ox-tools/blob/main/crates/cargo-anvil/docs/design/updates.md\n";

/// Repo-root-relative path of the one composed recipe file.
pub(crate) const ANVIL_JUST_PATH: &str = ".anvil/anvil.just";

/// Contents of `justfiles/anvil/versions.just` baked into the binary.
const VERSIONS_JUST: &str = include_str!("../../../templates/justfiles/anvil/versions.just");

/// Contents of `justfiles/anvil/tools.just` baked into the binary.
const TOOLS_JUST: &str = include_str!("../../../templates/justfiles/anvil/tools.just");

/// Contents of `justfiles/anvil/helpers.just` baked into the binary.
///
/// Holds the shared helper recipe `_anvil-base-ref` (reused by the impact
/// recipe and anvil-mutants-diff) and the bucket legend documenting how
/// per-check recipes consume the impact cache via `_anvil-impact-include`
/// (which, along with cache production and `_anvil-impact-format`, lives in
/// `impact.just`).
const HELPERS_JUST: &str = include_str!("../../../templates/justfiles/anvil/helpers.just");

/// Contents of `justfiles/anvil/impact.just` baked into the binary.
///
/// The single `anvil-impact` recipe: it snapshots the base ref and the
/// working tree (two independent cache keys), computes the cargo-delta
/// impact set, and writes the `target/anvil/impact/` artifacts that the
/// scoped checks consume via `_anvil-impact-include`. Also owns the tier
/// projection helper `_anvil-impact-format` (which lives here next to its
/// sole caller). The same recipe runs locally and in cloud workflows (which
/// just share the artifacts).
const IMPACT_JUST: &str = include_str!("../../../templates/justfiles/anvil/impact.just");

/// Emits `(path, include_str!)` pairs for a set of split recipe files that
/// live under a subdirectory of `justfiles/anvil/`. Each file is one owned
/// artifact, so the recipe tree is one file per check / per group rather
/// than a single monolithic `checks.just` / `groups.just`.
macro_rules! split_recipe_files {
    ($subdir:literal, [$($name:literal),* $(,)?]) => {
        &[$(
            (
                concat!("justfiles/anvil/", $subdir, "/", $name, ".just"),
                include_str!(concat!("../../../templates/justfiles/anvil/", $subdir, "/", $name, ".just")),
            ),
        )*]
    };
}

/// Generic local-development recipes that are not cloud check-group members.
const DEV_FILES: &[(&str, &str)] = split_recipe_files!("dev", ["build"]);

#[test]
fn aprz_delegates_github_cli_token_discovery_to_the_tool() {
    let aprz = CHECK_FILES
        .iter()
        .find_map(|(path, body)| path.ends_with("/aprz.just").then_some(*body))
        .expect("aprz.just is registered in CHECK_FILES below");
    assert!(aprz.contains("GITHUB_TOKEN"));
    assert!(aprz.contains("--github-token-from-gh"));
    assert!(!aprz.contains("gh auth token"));
}

/// One `justfiles/anvil/checks/<check>.just` file per catalog check
/// (the check recipe plus its paired `*-setup` / `*-validate-prereqs`).
const CHECK_FILES: &[(&str, &str)] = split_recipe_files!(
    "checks",
    [
        "aprz",
        "audit",
        "bench",
        "bolero",
        "careful",
        "cargo-hack",
        "cargo-sort",
        "clippy",
        "deny",
        "doc-build",
        "doc-test",
        "ensure-no-cyclic-deps",
        "ensure-no-default-features",
        "examples",
        "external-types",
        "fmt",
        "license-headers",
        "llvm-cov",
        "loom",
        "miri",
        "miri-race-coverage",
        "miri-strict-provenance",
        "miri-tree-borrows",
        "msrv-test",
        "mutants-diff",
        "mutants-full",
        "pr-title",
        "readme-check",
        "semver-check",
        "spellcheck",
        "udeps",
    ]
);

/// One `justfiles/anvil/groups/<group>.just` file per group (the group
/// recipe plus its paired `*-setup` / `*-validate-prereqs`).
const GROUP_FILES: &[(&str, &str)] = split_recipe_files!(
    "groups",
    [
        "pr-fast",
        "pr-msrv",
        "pr-slow",
        "pr-test",
        "pr-runtime-analysis",
        "pr-mutants",
        "scheduled-test",
        "scheduled-advisories",
        "scheduled-runtime-analysis",
        "scheduled-exhaustive",
    ]
);

/// Contents of `justfiles/anvil/tiers.just` baked into the binary.
const TIERS_JUST: &str = include_str!("../../../templates/justfiles/anvil/tiers.just");

/// Embedded body of the `anvil-imports` region in the user's Justfile.
pub(crate) const JUSTFILE_IMPORTS_BODY: &str = include_str!("../../../templates/regions/justfile-imports.just");

/// Region id for the imports block in the user's `Justfile`.
pub(crate) const JUSTFILE_REGION_ID: &str = "anvil-imports";

/// Canonical repo-root-relative path of the user's `Justfile`.
///
/// Capitalized to match the dominant Unix convention for repo-root
/// build-config files (`Makefile`, `Dockerfile`, `Rakefile`, ...). `just`
/// accepts either case, and the engine reuses whatever casing a repo already
/// has on disk.
pub(crate) const JUSTFILE_PATH: &str = "Justfile";

const JUSTFILE_SCAFFOLD: &str = "set unstable\n\
set windows-shell := [\"pwsh.exe\", \"-NoLogo\", \"-NoProfile\", \"-NonInteractive\", \"-Command\"]\n\n";

fn section(id: impl Into<String>, body: impl Into<String>) -> Artifact {
    Artifact::owned_file_section(ANVIL_JUST_PATH, id, body)
}

fn recipe_name(line: &str) -> Option<&str> {
    if line.is_empty() || line.len() != line.trim_start().len() || line.starts_with('#') || line.starts_with('[') || line.contains(":=") {
        return None;
    }
    let (head, _) = line.split_once(':')?;
    let name = head.split_whitespace().next()?;
    let generated_recipe_name =
        name.starts_with("anvil-") || name.starts_with("_anvil-") || name.starts_with("_install-") || name.starts_with("_check-");
    (generated_recipe_name && name.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))).then_some(name)
}

pub(crate) fn without_generated_header(body: &str) -> String {
    let normalized = body.replace("\r\n", "\n");
    normalized.strip_prefix(REPEATED_TEMPLATE_HEADER).unwrap_or(&normalized).to_owned()
}

pub(crate) fn template_sections(path: &str, body: &str) -> Vec<Artifact> {
    let normalized = without_generated_header(body);
    let body = normalized.as_str();
    let lines = body.split_inclusive('\n').collect::<Vec<_>>();
    let recipe_headers = lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| recipe_name(line.trim_end_matches(['\r', '\n'])).map(|name| (index, name.to_owned())))
        .collect::<Vec<_>>();

    if recipe_headers.is_empty() {
        return vec![section(format!("source:{path}"), body)];
    }

    let mut starts = Vec::with_capacity(recipe_headers.len());
    for (header, name) in recipe_headers {
        let mut start = header;
        while start > 0 {
            let preceding = lines[start - 1].trim_end_matches(['\r', '\n']);
            if preceding.is_empty() || preceding.starts_with('#') || preceding.starts_with('[') {
                start -= 1;
            } else {
                break;
            }
        }
        starts.push((start, name));
    }

    let mut out = Vec::with_capacity(starts.len() + 1);
    if starts[0].0 > 0 {
        out.push(section(format!("source:{path}"), lines[..starts[0].0].concat()));
    }
    for (index, (start, name)) in starts.iter().enumerate() {
        let end = starts.get(index + 1).map_or(lines.len(), |(next, _)| *next);
        out.push(section(format!("recipe:{name}"), lines[*start..end].concat()));
    }
    out
}

/// Header and `anvil` alias for the composed recipe file.
#[must_use]
pub fn entry() -> Artifact {
    section("alias:anvil", ENTRY_JUST)
}

/// One-time scaffold for a repository that has no root Justfile yet.
#[must_use]
pub(crate) const fn scaffold() -> &'static str {
    JUSTFILE_SCAFFOLD
}

/// Pinned toolchain and cargo-subcommand version declarations.
#[must_use]
pub fn versions() -> Vec<Artifact> {
    template_sections("versions", VERSIONS_JUST)
}

/// Tool install and prerequisite recipes.
#[must_use]
pub fn tools() -> Vec<Artifact> {
    template_sections("tools", TOOLS_JUST)
}

/// Shared helper recipes and impact contract.
#[must_use]
pub fn helpers() -> Vec<Artifact> {
    template_sections("helpers", HELPERS_JUST)
}

/// Shared `anvil-impact` recipe.
#[must_use]
pub fn impact() -> Vec<Artifact> {
    template_sections("impact", IMPACT_JUST)
}

/// Generic local-development recipe files.
#[must_use]
pub fn dev_files() -> Vec<Artifact> {
    DEV_FILES.iter().flat_map(|&(path, body)| template_sections(path, body)).collect()
}

/// The `justfiles/anvil/checks/<check>.just` files — one owned artifact
/// per catalog check.
#[must_use]
pub fn check_files() -> Vec<Artifact> {
    CHECK_FILES.iter().flat_map(|&(path, body)| template_sections(path, body)).collect()
}

/// The `justfiles/anvil/groups/<group>.just` files — one owned artifact
/// per group.
#[must_use]
pub fn group_files() -> Vec<Artifact> {
    GROUP_FILES.iter().flat_map(|&(path, body)| template_sections(path, body)).collect()
}

/// `justfiles/anvil/tiers.just` — the tier aggregators.
#[must_use]
pub fn tiers() -> Vec<Artifact> {
    template_sections("tiers", TIERS_JUST)
}

/// Look up one built-in Just recipe by its top-level name.
///
/// This is the preferred entry point for a derived catalog that wants to
/// replace or remove one recipe without taking ownership of neighboring
/// declarations in the source template.
#[must_use]
pub fn recipe(name: &str) -> Option<Artifact> {
    let id = format!("recipe:{name}");
    tools()
        .into_iter()
        .chain(versions())
        .chain(helpers())
        .chain(impact())
        .chain(tiers())
        .chain(dev_files())
        .chain(check_files())
        .chain(group_files())
        .find(|artifact| {
            matches!(
                artifact,
                Artifact::OwnedFileSection(section) if section.id == id
            )
        })
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};
    use std::process::Command;

    use ImpactPolicy::{Affected, Modified, Required, Unscoped};
    use tempfile::TempDir;

    use super::*;
    use crate::Catalog;

    /// A check's impact-scoping policy: either unscoped (always runs the full
    /// workspace) or scoped to one cargo-delta impact category.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum ImpactPolicy {
        Unscoped,
        Modified,
        Affected,
        Required,
    }

    impl ImpactPolicy {
        /// The `_anvil-impact-include` category argument this policy emits, or
        /// `None` when the check is unscoped and takes no impact dependency.
        fn category(self) -> Option<&'static str> {
            match self {
                Self::Unscoped => None,
                Self::Modified => Some("modified"),
                Self::Affected => Some("affected"),
                Self::Required => Some("required"),
            }
        }
    }

    /// The intended impact policy for every catalog check -- the canonical
    /// mapping `every_check_matches_its_declared_impact_policy` enforces
    /// against the emitted recipes. Keep in sync with the check mapping table
    /// in the design docs.
    const EXPECTED_CHECK_POLICY: &[(&str, ImpactPolicy)] = {
        &[
            ("aprz", Unscoped),
            ("audit", Unscoped),
            ("bench", Affected),
            ("bolero", Affected),
            ("careful", Affected),
            ("cargo-hack", Required),
            ("cargo-sort", Modified),
            ("clippy", Affected),
            ("deny", Unscoped),
            ("doc-build", Required),
            ("doc-test", Affected),
            ("ensure-no-cyclic-deps", Modified),
            ("ensure-no-default-features", Modified),
            ("examples", Affected),
            ("external-types", Affected),
            ("fmt", Modified),
            ("license-headers", Modified),
            ("llvm-cov", Affected),
            ("loom", Affected),
            ("miri", Affected),
            ("miri-race-coverage", Affected),
            ("miri-strict-provenance", Affected),
            ("miri-tree-borrows", Affected),
            ("msrv-test", Affected),
            ("mutants-diff", Affected),
            ("mutants-full", Unscoped),
            ("pr-title", Unscoped),
            // readme-check + spellcheck are unscoped: their inputs (workspace
            // README template, root .spelling dictionary) are repo-level files
            // cargo-delta does not map to a package, so scoping them would
            // silently skip a changed template/dictionary.
            ("readme-check", Unscoped),
            ("semver-check", Affected),
            ("spellcheck", Unscoped),
            ("udeps", Required),
        ]
    };

    #[test]
    fn tools_just_template_is_not_empty() {
        assert!(TOOLS_JUST.contains("installed_cargo_tools := `cargo install --list`"));
        assert!(TOOLS_JUST.contains("anvil-tool-cargo-deny-install"));
        assert!(TOOLS_JUST.contains("anvil-tool-cargo-deny-validate-prereqs"));
        assert!(TOOLS_JUST.contains("anvil-component-default-clippy-install"));
        assert!(TOOLS_JUST.contains("anvil-toolchain-stable-install"));
        assert!(TOOLS_JUST.contains("anvil-toolchain-nightly-install"));
    }

    #[cfg_attr(miri, ignore = "spawns just; miri isolation forbids it")]
    #[test]
    fn composed_justfile_parses() {
        let body = Catalog::anvil()
            .artifacts()
            .iter()
            .filter_map(|artifact| match artifact {
                Artifact::OwnedFileSection(section) if section.path == ANVIL_JUST_PATH => Some(section.body.trim_end_matches('\n')),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("\n\n");
        assert_eq!(
            body.matches("GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.").count(),
            1,
            "the composed file must carry one generated-content header"
        );
        let temp = TempDir::new().expect("temporary Justfile directory must be creatable");
        let path = temp.path().join("anvil.just");
        std::fs::write(&path, body).expect("composed Justfile fixture must be writable");

        let output = Command::new("just")
            .args(["--unstable", "--justfile"])
            .arg(&path)
            .arg("--dump")
            .output()
            .expect("just must be available for generated-recipe tests");
        assert!(
            output.status.success(),
            "composed Justfile did not parse:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    #[test]
    fn recipes_are_independently_addressable_catalog_sections() {
        let recipe = recipe("anvil-clippy").expect("the built-in clippy recipe must be addressable");
        let Artifact::OwnedFileSection(section) = recipe else {
            panic!("a Just recipe must be an owned-file section");
        };
        assert_eq!(section.path, ANVIL_JUST_PATH);
        assert_eq!(section.id, "recipe:anvil-clippy");
        assert!(section.body.contains("anvil-clippy:"));
        assert!(!section.body.contains("anvil-clippy-setup"));
    }

    #[test]
    fn recipe_section_ids_are_unique() {
        let mut ids = BTreeSet::new();
        for artifact in tools()
            .into_iter()
            .chain(versions())
            .chain(helpers())
            .chain(impact())
            .chain(tiers())
            .chain(dev_files())
            .chain(check_files())
            .chain(group_files())
        {
            let Artifact::OwnedFileSection(section) = artifact else {
                continue;
            };
            assert!(ids.insert(section.id.clone()), "duplicate Just section id: {}", section.id);
        }
    }

    #[test]
    fn shared_assignments_live_in_the_tools_preamble() {
        let preamble = tools()
            .into_iter()
            .find(|artifact| {
                matches!(
                    artifact,
                    Artifact::OwnedFileSection(section) if section.id == "source:tools"
                )
            })
            .expect("tools preamble must be independently addressable");
        assert!(preamble.body().contains("bolero_command_prefix :="));
        assert!(preamble.body().contains("mutants_command_prefix :="));
        assert!(
            !recipe("anvil-tool-cargo-audit-validate-prereqs")
                .unwrap()
                .body()
                .contains("bolero_command_prefix :=")
        );
        assert!(
            !recipe("anvil-tool-cargo-llvm-cov-validate-prereqs")
                .unwrap()
                .body()
                .contains("mutants_command_prefix :=")
        );
    }

    /// All `checks/*.just` bodies concatenated, for content assertions.
    fn all_check_bodies() -> String {
        CHECK_FILES.iter().map(|(_, b)| *b).collect::<Vec<_>>().join("\n")
    }

    /// All `groups/*.just` bodies concatenated, for content assertions.
    fn all_group_bodies() -> String {
        GROUP_FILES.iter().map(|(_, b)| *b).collect::<Vec<_>>().join("\n")
    }

    fn defines_recipe(body: &str, recipe: &str) -> bool {
        body.lines().any(|line| {
            line.strip_prefix(recipe)
                .is_some_and(|suffix| suffix.starts_with(':') || suffix.starts_with(' '))
        })
    }

    #[test]
    fn checks_just_template_includes_all_catalog_checks() {
        let checks = all_check_bodies();
        for needle in [
            "anvil-fmt",
            "anvil-clippy",
            "anvil-license-headers",
            "anvil-pr-title",
            "anvil-llvm-cov",
            "anvil-doc-test",
            "anvil-mutants-diff",
            "anvil-miri",
            "anvil-mutants-full",
            "anvil-bench",
        ] {
            assert!(defines_recipe(&checks, needle), "checks tree missing recipe '{needle}'");
        }
    }

    #[test]
    fn checks_fail_closed_and_preserve_opted_out_tests() {
        let checks = all_check_bodies();
        for needle in [
            "anvil-bolero: target discovery failed",
            "${prefix}: cargo metadata failed",
            "coverage-gate '{packages}' run",
            "could not resolve the cargo-careful executable",
            "mutants_command_prefix",
        ] {
            assert!(checks.contains(needle), "checks tree missing safety behavior '{needle}'");
        }
        for needle in ["Inconclusive comparisons", "an unbuildable baseline is not evidence"] {
            assert!(checks.contains(needle), "checks tree missing advisory behavior '{needle}'");
        }
        assert!(
            checks.contains("bolero list --profile release --package '{name}'"),
            "bolero discovery must use the execution profile through cargo-each"
        );
        assert!(
            checks.contains("bolero test --profile release --engine libfuzzer"),
            "bolero execution must use the profile option accepted by the pinned cargo-bolero"
        );
        assert!(
            !checks.contains("bolero list @bareArgs"),
            "bolero discovery must not pass repeated --package arguments"
        );
        assert!(!checks.contains("bolero list failed; assuming no targets"));
    }

    #[test]
    fn installers_are_portable_and_binary_mode_never_compiles() {
        assert!(
            TOOLS_JUST.contains("installed_cargo_tools := `cargo install --list`"),
            "tool inventory must be a lazy direct Cargo invocation"
        );
        assert!(
            TOOLS_JUST.contains("semver_matches(installed, \">=\" + minimum)"),
            "validation must accept equal or newer tool versions"
        );
        assert!(
            TOOLS_JUST.contains("binstall --no-confirm --locked --disable-strategies compile"),
            "binary policy must not fall back to source compilation"
        );
    }

    #[test]
    fn each_check_file_defines_its_own_check_recipe() {
        // The file `checks/<name>.just` must define `anvil-<name>` -- guards
        // against a mis-split that files a check's recipe under the wrong name.
        for (path, body) in CHECK_FILES {
            let stem = path
                .strip_prefix("justfiles/anvil/checks/")
                .and_then(|p| p.strip_suffix(".just"))
                .expect("check file path has the expected shape");
            let recipe = format!("anvil-{stem}");
            assert!(defines_recipe(body, &recipe), "{path} must define '{recipe}'");
        }
    }

    #[test]
    fn impact_scoped_checks_consume_package_files_through_cargo_each() {
        let mut scoped = 0;
        for (path, body) in CHECK_FILES {
            for category in ["modified", "affected", "required"] {
                if !body.contains(&format!("anvil_{category}_selection")) {
                    continue;
                }
                scoped += 1;
                assert!(
                    body.contains(" each "),
                    "{path} must delegate package-file consumption to cargo-each"
                );
            }
        }
        assert!(scoped >= 15, "the impact-scoped check set unexpectedly collapsed");
    }

    #[test]
    fn miri_profiles_inherit_the_cargo_each_runner() {
        let miri = CHECK_FILES
            .iter()
            .find_map(|(path, body)| path.ends_with("/miri.just").then_some(*body))
            .expect("miri.just is registered in CHECK_FILES");
        for needle in [
            "_anvil-miri-test profile package=\"\" test_filter=\"\" example=\"\": anvil-impact",
            "cargo '+{{ rust_nightly }}' each",
            "--exclude-filter 'metadata:anvil.miri.exclude=true'",
            "--jobs {{ anvil_miri_jobs }}",
            "--keep-going",
            "miri test --package '{spec}'",
        ] {
            assert!(miri.contains(needle), "miri runner is missing '{needle}'");
        }

        for (check, profile) in [
            ("miri", "standard"),
            ("miri-tree-borrows", "tree-borrows"),
            ("miri-strict-provenance", "strict-provenance"),
            ("miri-race-coverage", "race-coverage"),
        ] {
            let body = CHECK_FILES
                .iter()
                .find_map(|(path, body)| path.ends_with(&format!("/{check}.just")).then_some(*body))
                .unwrap_or_else(|| panic!("{check}.just is registered in CHECK_FILES"));
            let dependency = if check == "miri" {
                format!("(_anvil-miri-test \"{profile}\" package test example)")
            } else {
                format!("(_anvil-miri-test \"{profile}\")")
            };
            assert!(
                body.contains(&dependency),
                "{check}.just must inherit the shared Miri executable runner with its profile"
            );
            assert!(
                !body.contains("& \"{{ just_executable() }}\" _anvil-miri-test"),
                "{check}.just must not launch the main Miri runner through a nested just process"
            );
        }
    }

    #[test]
    fn impact_recipe_writes_direct_package_file_artifacts() {
        assert!(IMPACT_JUST.contains("anvil-impact:"));
        for tier in ["modified", "affected", "required"] {
            assert!(IMPACT_JUST.contains(&format!("--{tier} --format packages")));
            assert!(IMPACT_JUST.contains(&format!("target/anvil/impact/{tier}.packages")));
            assert!(IMPACT_JUST.contains(&format!("anvil_{tier}_selection")));
        }
        assert!(!IMPACT_JUST.contains("ConvertFrom-Json"));
        assert!(!IMPACT_JUST.contains("_anvil-impact-format"));
    }

    #[test]
    fn every_check_matches_its_declared_impact_policy() {
        // Single source of truth for each check's impact policy. The catalog
        // encodes the policy structurally -- an `_anvil-impact-include
        // <category>` call, or its absence for unscoped checks -- and this
        // table pins the intended value. Pinning the exact category per check
        // (rather than a bare count) makes a check silently changing category,
        // or gaining/losing scoping, fail here instead of slipping through.
        let expected: BTreeMap<&str, ImpactPolicy> = EXPECTED_CHECK_POLICY.iter().copied().collect();
        assert_eq!(
            expected.len(),
            EXPECTED_CHECK_POLICY.len(),
            "EXPECTED_CHECK_POLICY contains a duplicate check entry"
        );
        let miri_runner = CHECK_FILES
            .iter()
            .find_map(|(path, body)| path.ends_with("/miri.just").then_some(*body))
            .expect("miri.just is registered in CHECK_FILES");

        let mut seen = BTreeSet::new();
        for (path, body) in CHECK_FILES {
            let stem = path
                .strip_prefix("justfiles/anvil/checks/")
                .and_then(|p| p.strip_suffix(".just"))
                .expect("check file path has the expected shape");
            seen.insert(stem);
            let policy = *expected
                .get(stem)
                .unwrap_or_else(|| panic!("check '{stem}' is missing from EXPECTED_CHECK_POLICY; classify it explicitly"));
            let execution_body = if body.contains("(_anvil-miri-test \"") { miri_runner } else { body };

            // Parse the package-file selector used by the recipe.
            let calls: Vec<&str> = ["modified", "affected", "required"]
                .into_iter()
                .filter(|cat| {
                    execution_body.contains(&format!("anvil_{cat}_selection")) || execution_body.contains(&format!("{cat}.packages"))
                })
                .collect();
            assert!(
                calls.len() <= 1,
                "{path} makes contradictory impact-include calls {calls:?}; a check resolves exactly one category"
            );
            let depends_on_impact = execution_body
                .lines()
                .filter(|line| !line.starts_with('#') && !line.chars().next().is_some_and(char::is_whitespace))
                .filter_map(|line| line.split_once(':'))
                .any(|(_, dependencies)| dependencies.split_whitespace().any(|dependency| dependency == "anvil-impact"));

            match policy.category() {
                None => {
                    // Unscoped: no cache dependency, no include call.
                    assert!(calls.is_empty(), "{path} is declared Unscoped but consumes an impact selection");
                    assert!(!depends_on_impact, "{path} is declared Unscoped but depends on anvil-impact");
                }
                Some(category) => {
                    assert_eq!(
                        calls.as_slice(),
                        &[category],
                        "{path}: declared {policy:?} but its package-file selection is {calls:?}"
                    );
                    // A scoped check must depend on anvil-impact so the package
                    // file is fresh and delegate its consumption to cargo-each.
                    assert!(
                        depends_on_impact,
                        "{path} reads the impact cache but does not depend on anvil-impact"
                    );
                    assert!(
                        execution_body.contains(" each "),
                        "{path} must delegate the selection to cargo-each"
                    );
                }
            }
            assert!(
                !body.contains("ANVIL_INCLUDE_"),
                "{path} must not reference the removed ANVIL_INCLUDE_* env vars"
            );
        }

        // Bijection: every declared check exists as a file, and every file is
        // declared -- so adding or removing a check forces an explicit policy.
        let declared: BTreeSet<&str> = expected.keys().copied().collect();
        assert_eq!(
            declared, seen,
            "EXPECTED_CHECK_POLICY and the check catalog disagree on the set of checks"
        );

        // Guard the headline scoped/unscoped split so a wholesale policy shift
        // is a deliberate, reviewed edit rather than an accident.
        let scoped = EXPECTED_CHECK_POLICY.iter().filter(|(_, p)| p.category().is_some()).count();
        let unscoped = EXPECTED_CHECK_POLICY.len() - scoped;
        assert_eq!(
            (scoped, unscoped),
            (24, 7),
            "impact scoped/unscoped split changed; update EXPECTED_CHECK_POLICY deliberately"
        );
    }

    #[test]
    fn semver_check_compares_against_the_pr_branch_baseline() {
        let (_, body) = CHECK_FILES
            .iter()
            .find(|(path, _)| *path == "justfiles/anvil/checks/semver-check.just")
            .expect("semver check template is registered");

        // The recipe must use the same base-ref expression as impact and pass
        // it to cargo-semver-checks
        // as the baseline rather than comparing against the last crates.io release.
        for needle in [
            "anvil_base_ref",
            "git rev-parse --verify \"$base^{commit}\"",
            "git cat-file -e $baselineManifest",
            "cargo {{ anvil_stable_toolchain_arg }} semver-checks --package $p --baseline-rev $base",
        ] {
            assert!(body.contains(needle), "semver check template missing '{needle}'");
        }
    }

    #[test]
    fn groups_just_template_includes_all_groups_and_pr_slow_groups() {
        let groups = all_group_bodies();
        for needle in [
            "anvil-pr-fast:",
            "anvil-pr-slow:",
            "anvil-pr-test:",
            "anvil-pr-msrv:",
            "anvil-pr-runtime-analysis:",
            "anvil-pr-mutants:",
            "anvil-scheduled-test:",
            "anvil-scheduled-advisories:",
            "anvil-scheduled-exhaustive:",
        ] {
            assert!(groups.contains(needle), "groups tree missing '{needle}'");
        }
        for needle in ["anvil-pr-slow1:", "anvil-pr-slow2:", "anvil-pr-slow3:"] {
            assert!(!groups.contains(needle), "groups tree still contains stale '{needle}'");
        }
        assert!(groups.contains(
            "anvil-pr-slow: anvil-pr-slow-validate-prereqs anvil-pr-test anvil-pr-msrv anvil-pr-runtime-analysis anvil-pr-mutants"
        ));
        // PR group recipes list their own validate-prereqs aggregate first so
        // all tool checks run up front (just dedups the per-check ones).
        for needle in [
            "anvil-pr-fast: anvil-pr-fast-validate-prereqs",
            "anvil-pr-test: anvil-pr-test-validate-prereqs",
            "anvil-pr-msrv: anvil-pr-msrv-validate-prereqs",
            "anvil-pr-runtime-analysis: anvil-pr-runtime-analysis-validate-prereqs",
            "anvil-pr-mutants: anvil-pr-mutants-validate-prereqs",
        ] {
            assert!(
                groups.contains(needle),
                "group recipe must run its validate-prereqs first: '{needle}'"
            );
        }
        // Scheduled groups are the full-workspace backstop: the public recipe
        // wraps in `_anvil-unscoped` (forcing ANVIL_IMPACT=off before the deps
        // run), and the private `_anvil-<group>` fan-out lists its
        // validate-prereqs aggregate first.
        for g in [
            "scheduled-test",
            "scheduled-advisories",
            "scheduled-runtime-analysis",
            "scheduled-exhaustive",
        ] {
            assert!(
                groups.contains(&format!("anvil-{g}: (_anvil-unscoped \"{g}\")")),
                "scheduled group {g} must wrap in _anvil-unscoped"
            );
            assert!(
                groups.contains(&format!("_anvil-{g}: anvil-{g}-validate-prereqs")),
                "scheduled group {g} private fan-out must run its validate-prereqs first"
            );
        }
    }

    #[test]
    fn impact_scoped_groups_declare_cargo_delta_prereq() {
        // Every PR group whose checks are impact-scoped depends (transitively,
        // via each scoped check) on `anvil-impact`, which invokes cargo-delta
        // when it (re)computes the impact set. The group's setup +
        // validate-prereqs must therefore install / verify cargo-delta, so a
        // missing tool fails fast at setup rather than mid-run. (pr-slow is an
        // umbrella and inherits this via pr-test / pr-msrv /
        // pr-runtime-analysis / pr-mutants.) Scheduled groups force
        // ANVIL_IMPACT=off and never
        // recompute the impact set, so they deliberately do NOT depend on
        // cargo-delta.
        let groups = all_group_bodies();
        for g in ["pr-fast", "pr-test", "pr-msrv", "pr-runtime-analysis", "pr-mutants"] {
            assert!(
                groups.contains(&format!(
                    "anvil-{g}-setup installer=\"install\": \\\n    (anvil-tool-cargo-delta-install installer)"
                )),
                "group {g} setup must install cargo-delta"
            );
            assert!(
                groups.contains(&format!(
                    "anvil-{g}-validate-prereqs: \\\n    anvil-tool-cargo-delta-validate-prereqs"
                )),
                "group {g} validate-prereqs must verify cargo-delta"
            );
        }
        // Scheduled groups force impact off and never recompute, so they must
        // NOT carry cargo-delta as a prerequisite.
        for g in [
            "scheduled-test",
            "scheduled-advisories",
            "scheduled-runtime-analysis",
            "scheduled-exhaustive",
        ] {
            assert!(
                !groups.contains(&format!(
                    "anvil-{g}-setup installer=\"install\": \\\n    (anvil-tool-cargo-delta-install installer)"
                )),
                "scheduled group {g} must not install cargo-delta (it forces ANVIL_IMPACT=off and never recomputes)"
            );
            assert!(
                !groups.contains(&format!(
                    "anvil-{g}-validate-prereqs: \\\n    anvil-tool-cargo-delta-validate-prereqs"
                )),
                "scheduled group {g} must not verify cargo-delta (it forces ANVIL_IMPACT=off and never recomputes)"
            );
        }
    }

    #[test]
    fn tiers_just_template_has_three_tiers() {
        for needle in ["anvil-pr:", "anvil-scheduled:", "anvil-full:", "_anvil-scheduled:", "_anvil-full:"] {
            assert!(TIERS_JUST.contains(needle), "tiers.just missing '{needle}'");
        }
        // Containerized execution is reached only through the explicit
        // `anvil-container` recipe, so no tier routes through a native/container
        // seam. The PR tier depends on its work directly. The scheduled and full
        // tiers are the full-workspace backstop for PR-tier impact scoping, so
        // they wrap a private `_anvil-<tier>` recipe that carries the
        // validate-prereqs aggregate (run first, so a missing tool fails up
        // front) and inherits ANVIL_IMPACT=off from the wrapper.
        assert!(!TIERS_JUST.contains("_anvil-run"), "tiers must not route through an execution seam");
        for needle in [
            "anvil-pr: anvil-pr-validate-prereqs",
            "anvil-scheduled: (_anvil-unscoped \"scheduled\")",
            "_anvil-scheduled: anvil-scheduled-validate-prereqs",
            "anvil-full: (_anvil-unscoped \"full\")",
            "_anvil-full: anvil-full-validate-prereqs",
        ] {
            assert!(TIERS_JUST.contains(needle), "tier wrapper missing '{needle}'");
        }
        // Scoping is disabled by a parent process, because `just` runs each
        // dependency as its own process and a dependency-only recipe's body
        // executes after its dependencies.
        assert!(
            HELPERS_JUST.contains("$env:ANVIL_IMPACT = 'off'"),
            "the wrapper must force ANVIL_IMPACT=off for the scheduled/full tiers"
        );
        // The scheduled tier must fan out to every scheduled group, including
        // runtime-analysis (a separate group from exhaustive).
        for needle in [
            "anvil-scheduled-test",
            "anvil-scheduled-advisories",
            "anvil-scheduled-runtime-analysis",
            "anvil-scheduled-exhaustive",
        ] {
            assert!(TIERS_JUST.contains(needle), "scheduled tier must reference group '{needle}'");
        }
        // The catch-all `anvil-setup` / `anvil-validate-prereqs` must also
        // install / verify cargo-delta (the impact tool), so a local
        // `just anvil-setup` provisions a complete environment even though
        // cargo-delta isn't wired into any per-group setup.
        assert!(
            TIERS_JUST
                .contains("anvil-setup installer=\"install\": (anvil-full-setup installer) (anvil-tool-cargo-delta-install installer)"),
            "anvil-setup must install cargo-delta"
        );
        assert!(
            TIERS_JUST.contains("anvil-validate-prereqs: anvil-full-validate-prereqs anvil-tool-cargo-delta-validate-prereqs"),
            "anvil-validate-prereqs must verify cargo-delta"
        );
    }

    #[test]
    fn versions_just_has_known_tools() {
        for needle in [
            "cargo_nextest_version",
            "cargo_llvm_cov_version",
            "cargo_deny_version",
            "cargo_each_version",
            "cargo_mutants_version",
        ] {
            assert!(VERSIONS_JUST.contains(needle), "versions.just missing variable '{needle}'");
        }
    }

    #[test]
    fn stable_toolchain_selection_is_scoped_to_each_command() {
        assert!(!VERSIONS_JUST.contains("export RUSTUP_TOOLCHAIN"));
        assert!(IMPACT_JUST.contains("anvil_stable_toolchain_arg :="));
        assert!(IMPACT_JUST.contains("+{workspace-rust-version}"));
        assert!(!TOOLS_JUST.contains("_anvil-resolve-stable"));
        assert!(!TOOLS_JUST.contains("[script(\"pwsh\""));
        assert!(TOOLS_JUST.contains("cargo each --workspace --once -- cargo "));
        assert!(TOOLS_JUST.contains("rustup component add --toolchain"));
        assert!(!TOOLS_JUST.contains("rustup target add --toolchain"));
    }

    #[test]
    fn setup_graph_owns_stable_toolchain_provisioning() {
        assert!(
            TOOLS_JUST.contains("anvil-toolchain-stable-install installer=\"install\": (anvil-tool-cargo-each-install installer)"),
            "cargo-each must bootstrap stable provisioning"
        );
        assert!(
            TOOLS_JUST.contains("cargo each --workspace --once -- rustup toolchain install '{workspace-rust-version}'"),
            "stable fallback must delegate workspace rust-version resolution to cargo-each"
        );
        assert!(
            TOOLS_JUST.contains("bolero_command_prefix"),
            "Bolero's platform gate must be a Just-time condition"
        );
        assert!(
            TOOLS_JUST.contains("mutants_command_prefix"),
            "cargo-mutants' platform gate must be a Just-time condition"
        );
        for component in ["clippy", "rustfmt"] {
            let expected =
                format!("anvil-component-default-{component}-install installer=\"install\": (anvil-toolchain-stable-install installer)");
            assert!(
                TOOLS_JUST.contains(&expected),
                "default component '{component}' must provision stable first"
            );
        }
        let checks = all_check_bodies();
        for check in ["bench", "doc-build", "doc-test", "examples", "loom"] {
            let setup = format!("anvil-{check}-setup installer=\"install\": (anvil-toolchain-stable-install installer)");
            let validation = format!("anvil-{check}-validate-prereqs: anvil-tool-rustc-validate-prereqs");
            assert!(checks.contains(&setup), "{check} setup must provision stable");
            assert!(
                checks.contains(&validation),
                "{check} validation must remain read-only prerequisite validation"
            );
        }
        assert!(
            !checks.contains("validate-prereqs: anvil-toolchain-stable-install"),
            "validate-prereqs recipes must never install stable"
        );
        assert!(TOOLS_JUST.contains("semver_matches(installed, \">=\" + minimum)"));

        let groups = all_group_bodies();
        assert!(
            groups.contains("(anvil-tool-cargo-delta-install installer)") && groups.contains("(anvil-bench-setup installer)"),
            "representative group setup paths must reach stable provisioning through Cargo-tool or stable-only leaf setup"
        );
        assert!(
            TIERS_JUST.contains("anvil-full-setup installer=\"install\":")
                && TIERS_JUST.contains("(anvil-pr-setup installer)")
                && TIERS_JUST.contains("anvil-setup installer=\"install\": (anvil-full-setup installer)"),
            "full and global setup must retain their transitive path to stable provisioning"
        );
    }

    #[test]
    fn checks_use_portable_stable_toolchain_selection() {
        let checks = all_check_bodies();
        assert!(checks.contains("anvil_stable_toolchain_arg"));
        assert!(!checks.contains("_anvil_stable_toolchain_args"));
    }

    #[test]
    fn entry_section_defines_the_default_alias_without_imports() {
        assert!(ENTRY_JUST.contains("alias anvil := anvil-pr"));
        assert!(!ENTRY_JUST.contains("import "));
    }

    #[test]
    fn versions_just_defines_both_nightly_pins() {
        assert!(VERSIONS_JUST.contains("rust_nightly :="), "versions.just missing rust_nightly");
        assert!(
            VERSIONS_JUST.contains("rust_nightly_external_types :="),
            "versions.just missing rust_nightly_external_types"
        );
    }

    #[test]
    fn checks_just_has_no_floating_nightly_invocations() {
        let checks = all_check_bodies();
        for line in checks.lines() {
            let stripped = line.split('#').next().unwrap_or("");
            assert!(
                !stripped.contains("+nightly "),
                "checks tree has a floating '+nightly' invocation: {line}"
            );
            assert!(
                !stripped.contains("'+nightly'"),
                "checks tree has a floating '+nightly' invocation: {line}"
            );
        }
    }

    #[test]
    fn justfile_imports_body_is_a_single_import_line() {
        let body = JUSTFILE_IMPORTS_BODY.trim();
        assert_eq!(body, "import '.anvil/anvil.just'");
    }

    #[cfg(any())]
    mod stable_toolchain_resolver_tests {
        #[cfg(unix)]
        use std::os::unix::fs::PermissionsExt;
        use std::path::{Path, PathBuf};
        use std::process::{Command, Output};
        use std::{env, fs};

        use tempfile::{Builder, TempDir};

        use super::{TOOLS_JUST, VERSIONS_JUST};

        #[derive(Clone, Copy)]
        enum ResolverOperation {
            StableArgs,
            InstallIfMissing,
            ValidateWorkspaceMsrv,
            MsrvToolchain,
            InstallMsrvIfNeeded,
        }

        fn fixture(cargo_toml: &str) -> TempDir {
            let temp = Builder::new()
                .prefix("anvil repo's [copy] (fork) ")
                .tempdir()
                .expect("temporary repository must be creatable");
            fs::write(temp.path().join("Cargo.toml"), cargo_toml).expect("manifest fixture must be writable");
            fs::write(temp.path().join("versions.just"), VERSIONS_JUST).expect("versions fixture must be writable");
            fs::write(temp.path().join("tools.just"), TOOLS_JUST).expect("tools fixture must be writable");
            fs::write(
                temp.path().join("Justfile"),
                concat!(
                    "set unstable\n",
                    "set windows-shell := [\"pwsh\", \"-NoProfile\", \"-Command\"]\n",
                    "import 'versions.just'\n",
                    "import 'tools.just'\n\n",
                    "[script(\"pwsh\", \"-NoProfile\")]\n",
                    "_anvil-test-stable-args:\n",
                    "    $stableArgs = {{_anvil_stable_toolchain_args}}\n",
                    "    if ($stableArgs.Count -eq 0) {\n",
                    "        Write-Output '@()'\n",
                    "        exit 0\n",
                    "    }\n",
                    "    $escaped = ([string] $stableArgs[0]).Replace(\"'\", \"''\")\n",
                    "    Write-Output (\"@('\" + $escaped + \"')\")\n\n",
                    "[script(\"pwsh\", \"-NoProfile\")]\n",
                    "_anvil-test-stable-command:\n",
                    "    & cargo {{_anvil_stable_toolchain_args}} --version\n",
                    "\n[script(\"pwsh\", \"-NoProfile\")]\n",
                    "_anvil-test-stable-command-after-chdir:\n",
                    "    Set-Location 'nested'\n",
                    "    & cargo {{_anvil_stable_toolchain_args}} --version\n",
                ),
            )
            .expect("Justfile fixture must be writable");
            temp
        }

        fn tools_available() -> bool {
            Command::new("just").arg("--version").output().is_ok() && Command::new("pwsh").arg("--version").output().is_ok()
        }

        fn tool_path(name: &str) -> Option<PathBuf> {
            let executable = format!("{name}{}", env::consts::EXE_SUFFIX);
            env::split_paths(&env::var_os("PATH").unwrap_or_default())
                .map(|directory| directory.join(&executable))
                .find(|candidate| candidate.is_file())
        }

        fn command(root: &Path) -> Command {
            let just = tool_path("just").expect("resolver tests call command only after tools_available confirms Just is on PATH");
            let mut command = Command::new(just);
            command
                .args(["--justfile"])
                .arg(root.join("Justfile"))
                .current_dir(root)
                .env_remove("ANVIL_MSRV_TOOLCHAIN")
                .env_remove("RUSTUP_TOOLCHAIN");
            command
        }

        fn command_for_operation(root: &Path, operation: ResolverOperation) -> Command {
            let mut command = command(root);
            match operation {
                ResolverOperation::StableArgs => {
                    command.arg("_anvil-test-stable-args");
                }
                ResolverOperation::InstallIfMissing => {
                    command.arg("anvil-toolchain-stable-install");
                }
                ResolverOperation::ValidateWorkspaceMsrv => {
                    command.args(["_anvil-resolve-stable", "validate-workspace-msrv"]);
                }
                ResolverOperation::MsrvToolchain => {
                    command.args(["_anvil-resolve-stable", "msrv"]);
                }
                ResolverOperation::InstallMsrvIfNeeded => {
                    command.args(["_anvil-resolve-stable", "install-msrv"]);
                }
            }
            command
        }

        fn run(root: &Path, operation: ResolverOperation, rustup_toolchain: Option<&str>) -> Output {
            let mut command = command_for_operation(root, operation);
            match rustup_toolchain {
                Some(value) => {
                    command.env("RUSTUP_TOOLCHAIN", value);
                }
                None => {
                    command.env_remove("RUSTUP_TOOLCHAIN");
                }
            }
            command
                .output()
                .expect("just must be available to test generated toolchain selection")
        }

        fn resolved(root: &Path, rustup_toolchain: Option<&str>) -> String {
            let output = run(root, ResolverOperation::StableArgs, rustup_toolchain);
            assert!(
                output.status.success(),
                "resolver failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            String::from_utf8(output.stdout)
                .expect("resolver output must be UTF-8")
                .trim()
                .to_owned()
        }

        fn normalized_diagnostic(output: &Output) -> String {
            format!(
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            )
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ")
        }

        fn path_without_rustup() -> std::ffi::OsString {
            let path = env::var_os("PATH").unwrap_or_default();
            let paths = env::split_paths(&path).filter(|directory| {
                !["rustup", "rustup.exe", "rustup.cmd", "rustup.ps1"]
                    .iter()
                    .any(|name| directory.join(name).is_file())
            });
            env::join_paths(paths).expect("PATH without rustup must be valid")
        }

        #[test]
        fn honors_environment_files_and_msrv_in_precedence_order() {
            if !tools_available() {
                return;
            }
            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let root = temp.path();
            assert_eq!(resolved(root, None), "@('+1.93')");

            assert_eq!(resolved(root, Some("custom-toolchain")), "@()");
            assert_eq!(resolved(root, Some("team's-toolchain")), "@()");

            fs::write(root.join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.94\"\n").expect("toolchain fixture must be writable");
            assert_eq!(resolved(root, None), "@()");
        }

        #[test]
        fn passes_selected_arguments_directly_to_cargo() {
            if !tools_available() {
                return;
            }
            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let shim = TempDir::new().expect("cargo shim directory must be creatable");
            #[cfg(windows)]
            {
                fs::write(shim.path().join("cargo.cmd"), "@echo off\r\necho %*\r\nexit /b 0\r\n").expect("Cargo shim must be writable");
            }
            #[cfg(unix)]
            {
                let cargo = shim.path().join("cargo");
                fs::write(&cargo, "#!/bin/sh\nprintf '%s\\n' \"$*\"\nexit 0\n").expect("Cargo shim must be writable");
                fs::set_permissions(&cargo, fs::Permissions::from_mode(0o755)).expect("Cargo shim must be executable");
            }
            let mut paths = vec![shim.path().to_path_buf()];
            paths.extend(env::split_paths(&env::var_os("PATH").unwrap_or_default()));
            let paths = env::join_paths(paths).expect("shim PATH must be valid");

            let output = command(temp.path())
                .arg("_anvil-test-stable-command")
                .env("RUSTUP_TOOLCHAIN", "team's-toolchain")
                .env("PATH", &paths)
                .output()
                .expect("direct stable Cargo command must run");
            assert!(
                output.status.success(),
                "direct stable Cargo command failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                String::from_utf8(output.stdout).expect("Cargo shim output must be UTF-8").trim(),
                "--version"
            );

            fs::write(temp.path().join("rust-toolchain.toml"), "[toolchain]\ncomponents = [\"clippy\"]\n")
                .expect("toolchain fixture must be writable");
            let output = command(temp.path())
                .arg("_anvil-test-stable-command")
                .env("PATH", &paths)
                .output()
                .expect("repository-selected Cargo command must run");
            assert!(
                output.status.success(),
                "repository-selected Cargo command failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                String::from_utf8(output.stdout).expect("Cargo shim output must be UTF-8").trim(),
                "--version"
            );

            fs::remove_file(temp.path().join("rust-toolchain.toml")).expect("toolchain fixture must be removable");
            let nested = temp.path().join("nested");
            fs::create_dir(&nested).expect("nested working directory must be creatable");

            let output = command(temp.path())
                .args(["--working-directory"])
                .arg(&nested)
                .arg("_anvil-test-stable-command")
                .env("PATH", &paths)
                .output()
                .expect("stable Cargo command with an explicit working directory must run");
            assert!(
                output.status.success(),
                "working-directory stable Cargo command failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                String::from_utf8(output.stdout).expect("Cargo shim output must be UTF-8").trim(),
                "+1.93 --version"
            );

            let output = command(temp.path())
                .arg("_anvil-test-stable-command-after-chdir")
                .env("PATH", paths)
                .output()
                .expect("stable Cargo command after Set-Location must run");
            assert!(
                output.status.success(),
                "Set-Location stable Cargo command failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                String::from_utf8(output.stdout).expect("Cargo shim output must be UTF-8").trim(),
                "+1.93 --version"
            );
        }

        #[test]
        fn installs_default_components_on_the_selected_stable_toolchain() {
            if !tools_available() {
                return;
            }
            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let shim = TempDir::new().expect("component shim directory must be creatable");
            let cargo_log = shim.path().join("cargo.log");
            let rustup_log = shim.path().join("rustup.log");
            #[cfg(windows)]
            {
                fs::write(
                    shim.path().join("cargo.cmd"),
                    "@echo off\r\n>>\"%ANVIL_CARGO_LOG%\" echo %*\r\nexit /b 1\r\n",
                )
                .expect("Cargo shim must be writable");
                fs::write(
                    shim.path().join("rustup.cmd"),
                    "@echo off\r\n>>\"%ANVIL_RUSTUP_LOG%\" echo %*\r\nexit /b 0\r\n",
                )
                .expect("rustup shim must be writable");
            }
            #[cfg(unix)]
            {
                for (name, log_variable, status) in [("cargo", "ANVIL_CARGO_LOG", 1), ("rustup", "ANVIL_RUSTUP_LOG", 0)] {
                    let executable = shim.path().join(name);
                    fs::write(
                        &executable,
                        format!("#!/bin/sh\nprintf '%s\\n' \"$*\" >> \"${log_variable}\"\nexit {status}\n"),
                    )
                    .expect("component shim must be writable");
                    fs::set_permissions(&executable, fs::Permissions::from_mode(0o755)).expect("component shim must be executable");
                }
            }
            let mut paths = vec![shim.path().to_path_buf()];
            paths.extend(env::split_paths(&env::var_os("PATH").unwrap_or_default()));
            let paths = env::join_paths(paths).expect("shim PATH must be valid");
            let run_install = |rustup_toolchain: Option<&str>| {
                let mut command = command(temp.path());
                command
                    .args(["_install-component", "default", "clippy"])
                    .env("ANVIL_CARGO_LOG", &cargo_log)
                    .env("ANVIL_RUSTUP_LOG", &rustup_log)
                    .env("PATH", &paths);
                if let Some(value) = rustup_toolchain {
                    command.env("RUSTUP_TOOLCHAIN", value);
                }
                command.output().expect("default component installation must run")
            };

            let output = run_install(Some("custom-toolchain"));
            assert!(
                output.status.success(),
                "override-selected component installation failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                fs::read_to_string(&cargo_log).expect("Cargo shim log must be readable").trim(),
                "clippy --version"
            );
            assert_eq!(
                fs::read_to_string(&rustup_log).expect("rustup shim log must be readable").trim(),
                "component add clippy"
            );

            fs::write(temp.path().join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.94\"\n")
                .expect("toolchain fixture must be writable");
            fs::write(&cargo_log, "").expect("Cargo shim log must be resettable");
            fs::write(&rustup_log, "").expect("rustup shim log must be resettable");
            let output = run_install(None);
            assert!(
                output.status.success(),
                "repository-selected component installation failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                fs::read_to_string(&cargo_log).expect("Cargo shim log must be readable").trim(),
                "clippy --version"
            );
            assert_eq!(
                fs::read_to_string(&rustup_log).expect("rustup shim log must be readable").trim(),
                "component add clippy"
            );

            fs::remove_file(temp.path().join("rust-toolchain.toml")).expect("toolchain fixture must be removable");
            fs::write(&cargo_log, "").expect("Cargo shim log must be resettable");
            fs::write(&rustup_log, "").expect("rustup shim log must be resettable");
            let output = run_install(None);
            assert!(
                output.status.success(),
                "MSRV-selected component installation failed: {}",
                normalized_diagnostic(&output)
            );
            assert_eq!(
                fs::read_to_string(&cargo_log).expect("Cargo shim log must be readable").trim(),
                "+1.93 clippy --version"
            );
            assert_eq!(
                fs::read_to_string(&rustup_log).expect("rustup shim log must be readable").trim(),
                "component add --toolchain 1.93 clippy"
            );
        }

        #[test]
        fn rejects_missing_or_too_new_workspace_msrvs() {
            if !tools_available() {
                return;
            }
            let missing = fixture("[workspace]\nresolver = \"2\"\n");
            let output = run(missing.path(), ResolverOperation::StableArgs, None);
            assert!(!output.status.success());
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("no root") && diagnostic.contains("[workspace.package]"),
                "unexpected resolver diagnostic: {diagnostic}"
            );

            let workspace =
                fixture("[workspace]\nresolver = \"2\"\nmembers = [\"a\", \"b\"]\n[workspace.package]\nrust-version = \"1.92\"\n");
            for (name, version) in [("a", "1.91"), ("b", "1.93")] {
                let member = workspace.path().join(name);
                fs::create_dir(&member).expect("member directory must be creatable");
                fs::write(
                    member.join("Cargo.toml"),
                    format!(
                        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\nrust-version = \"{version}\"\n[lib]\npath = \"lib.rs\"\n"
                    ),
                )
                .expect("member manifest must be writable");
                fs::write(member.join("lib.rs"), "").expect("member source must be writable");
            }

            let shim = TempDir::new().expect("Cargo shim directory must be creatable");
            let log = shim.path().join("cargo.log");
            fs::write(
                shim.path().join("cargo.ps1"),
                concat!(
                    "Add-Content -LiteralPath $env:ANVIL_TEST_LOG -Value ($args -join ' ')\n",
                    "$metadata = @{\n",
                    "    workspace_members = @('a-id', 'b-id')\n",
                    "    packages = @(\n",
                    "        @{ id = 'a-id'; name = 'a'; rust_version = '1.91' }\n",
                    "        @{ id = 'b-id'; name = 'b'; rust_version = $env:ANVIL_TEST_B_MSRV }\n",
                    "    )\n",
                    "}\n",
                    "$metadata | ConvertTo-Json -Depth 4 -Compress\n",
                    "exit 0\n",
                ),
            )
            .expect("Cargo shim must be writable");
            fs::write(
                shim.path().join("rustup.ps1"),
                concat!(
                    "if (($args -contains 'toolchain') -and ($args -contains 'list')) {\n",
                    "    $env:ANVIL_TEST_INSTALLED_TOOLCHAINS -split ';' | Where-Object { $_ }\n",
                    "}\n",
                    "exit 0\n",
                ),
            )
            .expect("rustup shim must be writable");
            let mut paths = vec![shim.path().to_path_buf()];
            paths.extend(env::split_paths(&env::var_os("PATH").unwrap_or_default()));
            let paths = env::join_paths(paths).expect("shim PATH must be valid");
            let run_validation = |b_msrv: &str, rustup_toolchain: Option<&str>, installed: &str| {
                let mut command = command(workspace.path());
                command
                    .args(["_anvil-resolve-stable", "validate-workspace-msrv"])
                    .env("ANVIL_TEST_B_MSRV", b_msrv)
                    .env("ANVIL_TEST_INSTALLED_TOOLCHAINS", installed)
                    .env("ANVIL_TEST_LOG", &log)
                    .env("PATH", &paths);
                if let Some(value) = rustup_toolchain {
                    command.env("RUSTUP_TOOLCHAIN", value);
                }
                command.output().expect("workspace MSRV validation must run")
            };

            let output = run_validation("1.92", None, "stable-x86_64-pc-windows-msvc");
            assert!(!output.status.success(), "validation must not auto-install a missing root MSRV");
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("root MSRV toolchain '1.92' is not installed") && diagnostic.contains("anvil-toolchain-stable-install"),
                "unexpected missing-toolchain diagnostic: {diagnostic}"
            );
            assert!(
                fs::read_to_string(&log).unwrap_or_default().is_empty(),
                "Cargo metadata must not run before the root MSRV is known to be installed"
            );

            let output = run_validation("1.93", None, "1.92-x86_64-pc-windows-msvc");
            assert!(!output.status.success());
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("newer than the root MSRV") && diagnostic.contains("b (1.93)") && !diagnostic.contains("a (1.91)"),
                "unexpected resolver diagnostic: {diagnostic}"
            );

            let output = run_validation("1.92.0", None, "1.92-x86_64-pc-windows-msvc");
            assert!(
                output.status.success(),
                "member MSRVs at or below the root must be compatible: {}",
                normalized_diagnostic(&output)
            );
            let calls = fs::read_to_string(&log).expect("Cargo shim log must be readable");
            assert!(
                calls.lines().all(|line| line.starts_with("+1.92 metadata ")),
                "workspace compatibility metadata must use the root MSRV toolchain:\n{calls}"
            );

            let output = run_validation("1.93", Some("explicit-toolchain"), "");
            assert!(output.status.success(), "explicit override must permit differing MSRVs");
        }

        #[test]
        fn diagnoses_missing_rustup_before_installing_a_toolchain() {
            if !tools_available() {
                return;
            }
            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let output = command_for_operation(temp.path(), ResolverOperation::InstallIfMissing)
                .env("PATH", path_without_rustup())
                .output()
                .expect("stable setup must run far enough to diagnose missing rustup");
            assert!(!output.status.success(), "stable setup without rustup must fail");
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("rustup not found")
                    && diagnostic.contains("https://rustup.rs")
                    && diagnostic.contains("ensure it is on PATH"),
                "unexpected missing-rustup diagnostic: {diagnostic}"
            );

            let output = command_for_operation(temp.path(), ResolverOperation::InstallIfMissing)
                .env("RUSTUP_TOOLCHAIN", "selected-stable")
                .env("PATH", path_without_rustup())
                .output()
                .expect("environment-selected setup must diagnose missing rustup");
            assert!(!output.status.success(), "environment selection without rustup must fail");
            assert!(
                normalized_diagnostic(&output).contains("rustup not found"),
                "environment selection must require rustup"
            );

            fs::write(temp.path().join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.93\"\n")
                .expect("toolchain fixture must be writable");
            let output = command_for_operation(temp.path(), ResolverOperation::InstallIfMissing)
                .env("PATH", path_without_rustup())
                .output()
                .expect("file-selected setup must diagnose missing rustup");
            assert!(!output.status.success(), "toolchain-file selection without rustup must fail");
            assert!(
                normalized_diagnostic(&output).contains("rustup not found"),
                "toolchain-file selection must require rustup"
            );
        }

        #[test]
        fn rejects_an_unpaired_internal_msrv_mapping_for_stable_selection() {
            if !tools_available() {
                return;
            }
            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let run_with_mapping = |root: &Path| {
                command(root)
                    .arg("_anvil-test-stable-args")
                    .env("ANVIL_MSRV_TOOLCHAIN", "ms-prod-1.93")
                    .output()
                    .expect("just must be available to test the generated toolchain selection")
            };

            let output = run_with_mapping(temp.path());
            assert!(!output.status.success(), "an unpaired internal MSRV mapping must fail");
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("ANVIL_MSRV_TOOLCHAIN")
                    && diagnostic.contains("without RUSTUP_TOOLCHAIN")
                    && diagnostic.contains("unset ANVIL_MSRV_TOOLCHAIN"),
                "unexpected resolver diagnostic: {diagnostic}"
            );
        }

        #[test]
        fn provisions_public_and_mapped_msrv_toolchains() {
            if !tools_available() {
                return;
            }
            let run_install = |root: &Path, mapped: Option<&str>, installed: &str, cargo_exit: i32| {
                let shim = TempDir::new().expect("toolchain shim directory must be creatable");
                let rustup_log = shim.path().join("rustup.log");
                let cargo_log = shim.path().join("cargo.log");
                let installed_output = installed
                    .lines()
                    .map(|line| format!("Write-Output '{line}'"))
                    .collect::<Vec<_>>()
                    .join("\n");
                fs::write(
                    shim.path().join("rustup.ps1"),
                    format!(
                        "Add-Content -LiteralPath $env:ANVIL_RUSTUP_LOG -Value ($args -join ' ')\n\
                         if (($args -contains 'toolchain') -and ($args -contains 'list')) {{ {installed_output} }}\n\
                         exit 0\n"
                    ),
                )
                .expect("rustup shim must be writable");
                fs::write(
                    shim.path().join("cargo.ps1"),
                    format!(
                        "Add-Content -LiteralPath $env:ANVIL_CARGO_LOG -Value ($args -join ' ')\n\
                         exit {cargo_exit}\n"
                    ),
                )
                .expect("cargo shim must be writable");
                let mut paths = vec![shim.path().to_path_buf()];
                paths.extend(env::split_paths(&env::var_os("PATH").unwrap_or_default()));
                let mut command = command(root);
                command
                    .args(["_anvil-resolve-stable", "install-msrv"])
                    .env("ANVIL_RUSTUP_LOG", &rustup_log)
                    .env("ANVIL_CARGO_LOG", &cargo_log)
                    .env("PATH", env::join_paths(paths).expect("shim PATH must be valid"));
                if let Some(value) = mapped {
                    command.env("ANVIL_MSRV_TOOLCHAIN", value);
                }
                let output = command.output().expect("pwsh must be available to test MSRV provisioning");
                let rustup_calls = fs::read_to_string(rustup_log).unwrap_or_default();
                let cargo_calls = fs::read_to_string(cargo_log).unwrap_or_default();
                (output, rustup_calls, cargo_calls)
            };

            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");

            let (output, rustup_calls, cargo_calls) = run_install(
                temp.path(),
                None,
                "nightly-2026-01-01-x86_64-pc-windows-msvc\n1.93-x86_64-pc-windows-msvc",
                0,
            );
            assert!(
                output.status.success(),
                "installed public MSRV provisioning failed: {}",
                normalized_diagnostic(&output)
            );
            assert!(rustup_calls.contains("toolchain list"));
            assert!(
                !rustup_calls.contains("toolchain install"),
                "installed MSRV must not be reinstalled"
            );
            assert!(cargo_calls.is_empty(), "public MSRV availability is checked through rustup");

            let (output, rustup_calls, cargo_calls) = run_install(
                temp.path(),
                None,
                "nightly-2026-01-01-x86_64-pc-windows-msvc\n1.93.0-x86_64-pc-windows-msvc",
                0,
            );
            assert!(
                output.status.success(),
                "distinct patch-qualified installation must not prevent provisioning the selected MSRV: {}",
                normalized_diagnostic(&output)
            );
            assert!(
                rustup_calls.contains("toolchain install 1.93 --profile minimal"),
                "the exact 1.93 selector must be installed when only 1.93.0 exists"
            );
            assert!(cargo_calls.is_empty(), "public MSRV availability is checked through rustup");

            let (output, rustup_calls, cargo_calls) = run_install(temp.path(), Some("ms-prod-1.93"), "", 0);
            assert!(
                output.status.success(),
                "mapped MSRV provisioning failed: {}",
                normalized_diagnostic(&output)
            );
            assert!(cargo_calls.contains("+ms-prod-1.93 --version"));
            assert!(!rustup_calls.contains("toolchain list"));
            assert!(!rustup_calls.contains("toolchain install"));

            let (output, _, cargo_calls) = run_install(temp.path(), Some("ms-prod-1.93"), "", 9);
            assert!(!output.status.success(), "an unavailable mapped MSRV must fail");
            assert!(cargo_calls.contains("+ms-prod-1.93 --version"));
            let diagnostic = normalized_diagnostic(&output);
            assert!(
                diagnostic.contains("mapped MSRV toolchain")
                    && diagnostic.contains("is unavailable")
                    && diagnostic.contains("provision")
                    && diagnostic.contains("ANVIL_MSRV_TOOLCHAIN"),
                "unexpected mapped MSRV diagnostic: {diagnostic}"
            );
        }

        #[test]
        fn resolves_msrv_whenever_the_root_declares_one() {
            if !tools_available() {
                return;
            }
            let no_msrv = fixture("[workspace]\nresolver = \"2\"\n");
            fs::write(no_msrv.path().join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.94\"\n")
                .expect("toolchain fixture must be writable");
            let output = run(no_msrv.path(), ResolverOperation::InstallMsrvIfNeeded, None);
            assert!(
                output.status.success(),
                "a repository without a declared MSRV must not provision an MSRV"
            );
            let output = run(no_msrv.path(), ResolverOperation::MsrvToolchain, None);
            assert!(
                output.status.success(),
                "a repository without a declared MSRV must skip the MSRV test"
            );
            assert!(
                String::from_utf8(output.stdout)
                    .expect("resolver output must be UTF-8")
                    .trim()
                    .is_empty()
            );

            let temp = fixture("[workspace.package]\nrust-version = \"1.93\"\n");
            let root = temp.path();
            let output = run(root, ResolverOperation::ValidateWorkspaceMsrv, Some("explicit-toolchain"));
            assert!(
                output.status.success(),
                "an explicit stable override must bypass root-MSRV workspace validation"
            );
            let resolve_msrv = |root: &Path| {
                let output = run(root, ResolverOperation::MsrvToolchain, None);
                assert!(
                    output.status.success(),
                    "MSRV resolution failed: {}",
                    String::from_utf8_lossy(&output.stderr)
                );
                String::from_utf8(output.stdout)
                    .expect("resolver output must be UTF-8")
                    .trim()
                    .to_owned()
            };

            assert_eq!(resolve_msrv(root), "1.93");
            fs::write(root.join("rust-toolchain.toml"), "[toolchain]\ncomponents = [\"clippy\"]\n")
                .expect("toolchain fixture must be writable");
            assert_eq!(resolve_msrv(root), "1.93");

            fs::write(root.join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.93.0\"\n").expect("toolchain fixture must be writable");
            assert_eq!(resolve_msrv(root), "1.93");

            fs::write(root.join("rust-toolchain.toml"), "[toolchain]\nchannel = \"1.94\"\n").expect("toolchain fixture must be writable");
            assert_eq!(resolve_msrv(root), "1.93");
            let output = command(root)
                .args(["_anvil-resolve-stable", "msrv"])
                .env("ANVIL_MSRV_TOOLCHAIN", "ms-prod-1.93")
                .output()
                .expect("just must be available to test the generated resolver recipe");
            assert!(output.status.success());
            assert_eq!(
                String::from_utf8(output.stdout).expect("resolver output must be UTF-8").trim(),
                "ms-prod-1.93"
            );

            fs::write(root.join("rust-toolchain.toml"), "[toolchain]\npath = \"toolchains/custom\"\n")
                .expect("toolchain fixture must be writable");
            assert_eq!(resolve_msrv(root), "1.93");
        }
    }
}
