#!/usr/bin/env bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.
# Update cargo-anvil and regenerate; repository-specific edits stop automatic updates.
# Update behaviour: https://github.com/microsoft/ox-tools/blob/main/crates/cargo-anvil/docs/design/updates.md

log="$RUNNER_TEMP/anvil-$ANVIL_GROUP.log"
set +e
just "anvil-$ANVIL_GROUP" 2>&1 | tee "$log"
status=${PIPESTATUS[0]}
set -e

failed_recipe="$(sed -n 's/^error: recipe `\([^`]*\)` failed with exit code [0-9][0-9]*$/\1/p' "$log" | tail -n 1)"
echo "failed_recipe=${failed_recipe:-anvil-$ANVIL_GROUP}" >> "$GITHUB_OUTPUT"
echo "exit_code=$status" >> "$GITHUB_OUTPUT"
