# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# Owned by cargo-ox-check; edit via `cargo ox-check update`.
# The token __DEFAULT_BRANCH__ is substituted by cargo-ox-check at emit
# time with the repo's default branch.
name: ox-check-pr

on:
  pull_request:
    branches: [__DEFAULT_BRANCH__]
  merge_group: {}

permissions:
  contents: read

concurrency:
  group: ox-check-pr-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ox-check-pr:
    uses: ./.github/workflows/ox-check-pr-impl.yml
    permissions:
      contents: read
      pull-requests: read
