// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#![cfg(not(all(test, miri)))]
#![forbid(
    unsafe_code,
    reason = "every raw platform call in this workspace lives in `cargo-gamma-unsafe`, behind a safe interface; enforcing that here is what makes it a property the compiler checks rather than a convention people remember"
)]

//! Inert attribute macros for controlling and suppressing mutations generated by
//! [`cargo-gamma`](https://crates.io/crates/cargo-gamma).
//!
//! ```rust
//! #[gamma::skip]
//! fn hand_verified(x: u32) -> u32 {
//!     x + 1
//! }
//!
//! #[gamma::skip(arith, reason = "fixed-point math, checked by proptest")]
//! fn scaled(a: i64, b: i64) -> i64 {
//!     a * b / 1000
//! }
//!
//! #[gamma::test_timeout_multiplier(3.0)]
//! fn slow_algorithm(data: &[u8]) -> usize {
//!     data.len() * 2
//! }
//! ```
//!
//! Every macro in this crate expands to the annotated item unchanged. The attributes exist so
//! that `cargo-gamma` can see them, and so that a typo in a selector list or invalid argument is a
//! compile error in your crate rather than a silently ineffective directive.
//!
//! # Depending on it
//!
//! ```toml
//! [dependencies]
//! cargo-gamma-attrs = "0.1"
//! ```
//!
//! The package is `cargo-gamma-attrs` but its library is named `gamma`, which is what lets the
//! attributes be written as `#[gamma::skip]` with no `use` and no rename in the manifest. That
//! spelling matters more than it looks: it is the same text as the comment form, so the two
//! channels stay character-for-character identical and one can become the other by deleting two
//! slashes.
//!
//! An ordinary dependency rather than a dev-dependency, because these attributes are written on the
//! code being measured rather than on the tests measuring it, and `cargo build` compiles a library
//! target without its dev-dependencies. The crates are tiny and the attributes expand to nothing,
//! so what ships is a build-time dependency and no code. A crate that would rather not carry one at
//! all has the comment form, which needs no dependency whatever:
//!
//! ```text
//! // #[gamma::skip(arith)]
//! fn scaled(a: i64, b: i64) -> i64 { a * b / 1000 }
//! ```
//!
//! # The vocabulary
//!
//! Arguments are the same selector language the command line and the config file use, so one name
//! learned is one name that works everywhere. A selector is a mutator name (`arith.add_to_sub`), a
//! family prefix (`arith`), a profile (`@arithmetic`), or an academic alias (`ROR`); `!` in front
//! removes one from the set, and selectors apply left to right, so `arith, !arith.add_to_sub`
//! means what it reads as. No arguments at all means every mutator.
//!
//! ```rust
//! // Every mutator.
//! #[gamma::skip]
//! fn everything() {}
//!
//! // One mutator, by its full name.
//! #[gamma::skip(relational.lt_to_le)]
//! fn one_mutator(a: u32, b: u32) -> bool {
//!     a < b
//! }
//!
//! // A whole family.
//! #[gamma::skip(literal)]
//! fn a_family() -> &'static str {
//!     "not asserted on"
//! }
//!
//! // A profile.
//! #[gamma::skip(@arithmetic)]
//! fn a_profile(a: i32, b: i32) -> i32 {
//!     a * b + 1
//! }
//!
//! // An academic alias, matched case-insensitively.
//! #[gamma::skip(ROR)]
//! fn an_alias(a: u32, b: u32) -> bool {
//!     a >= b
//! }
//!
//! // A family, minus one of its members.
//! #[gamma::skip(arith, !arith.add_to_sub)]
//! fn all_but_one(a: i32, b: i32) -> i32 {
//!     a * b - 1
//! }
//! ```
//!
//! Two optional named arguments may follow the selectors:
//!
//! - `reason = "..."` — why the suppression exists. It is carried into the report, so a reviewer
//!   meets the justification beside the number rather than having to go and find the line.
//! - `tag = "..."` — a label for grouping suppressions, so a project can audit "everything we
//!   skipped for performance" as a set.
//!
//! ```rust
//! #[gamma::skip(stmt, reason = "instrumentation only", tag = "telemetry")]
//! fn record(counter: &mut u64) {
//!     *counter += 1;
//! }
//! ```
//!
//! Both must be string literals. Writing `reason = performance` or `reason("...")` is a compile
//! error, which is the point: a suppression that does not parse should fail loudly rather than
//! quietly cover nothing.
//!
//! These next four examples are compiled and required to *fail*, because the claim above is the
//! whole reason this crate exists and asserting it anywhere else would only prove that a token
//! stream containing `compile_error!` was produced — not that a user's build stops. The failure
//! reaches the user's build or it does not, and only compiling one can tell.
//!
//! ```compile_fail
//! // `reason` is not a string literal.
//! #[gamma::skip(reason = performance)]
//! fn scaled(a: i64) -> i64 {
//!     a * 2
//! }
//! ```
//!
//! ```compile_fail
//! // `reason` is called rather than assigned.
//! #[gamma::skip(reason("hand verified"))]
//! fn scaled(a: i64) -> i64 {
//!     a * 2
//! }
//! ```
//!
//! ```compile_fail
//! // `tag` is a number.
//! #[gamma::expect_survived(literal, tag = 7)]
//! fn describe(n: usize) -> String {
//!     format!("{n} items")
//! }
//! ```
//!
//! ```compile_fail
//! // The same rule applies however deeply the argument is nested.
//! #[gamma::expect_killed(a(b(tag = 7)))]
//! fn checksum(bytes: &[u8]) -> usize {
//!     bytes.len()
//! }
//! ```
//!
//! ```compile_fail
//! // A named value ends at the literal, so a selector-free typo cannot become `skip` for all.
//! #[gamma::skip(reason = "hand verified" + unexpected)]
//! fn scaled(a: i64) -> i64 {
//!     a * 2
//! }
//! ```
//!
//! The item itself still parses in every one of those cases: the macro expands to the item
//! *preceded* by the `compile_error!`, so the build reports the malformed attribute and nothing
//! else. An expansion that swallowed the item would bury one honest diagnostic under every use of
//! the function it annotated.
//!
//! ```compile_fail
//! #[gamma::skip(reason = performance)]
//! fn scaled(a: i64) -> i64 {
//!     a * 2
//! }
//!
//! // Resolves, which it could not if the attribute had eaten the item it was written on. The only
//! // error this example produces is the one about `reason`.
//! fn caller() -> i64 {
//!     scaled(21)
//! }
//! ```
//!
//! # The suppression macros
//!
//! [`macro@skip`] withdraws mutants. [`macro@expect_survived`] and [`macro@expect_killed`] assert
//! the opposite things about them and fail the run when the assertion breaks: the first is a
//! ratchet for a known gap, so that closing it is deliberate and visible rather than accidental,
//! and the second pins a test whose value someone wants protected from erosion.
//!
//! ```rust
//! // Records a gap. If someone later writes a test that kills these mutants, the run fails until
//! // the attribute is removed — so the gap closes on purpose, with the record cleaned up.
//! #[gamma::expect_survived(literal, reason = "log text is deliberately not asserted on")]
//! fn describe(n: usize) -> String {
//!     format!("processed {n} items")
//! }
//!
//! // Pins a guarantee. If a refactor weakens the suite until one of these mutants survives, the
//! // run fails immediately rather than after the score has slowly drifted.
//! #[gamma::expect_killed]
//! fn checksum(bytes: &[u8]) -> u32 {
//!     bytes.iter().fold(0u32, |acc, b| {
//!         acc.wrapping_mul(31).wrapping_add(u32::from(*b))
//!     })
//! }
//!
//! // Both take the same selectors, so an expectation can be as narrow as a suppression.
//! #[gamma::expect_killed(relational, reason = "the boundary tests exist to catch exactly these")]
//! fn in_range(x: i32, low: i32, high: i32) -> bool {
//!     x >= low && x <= high
//! }
//! ```
//!
//! # Stating a value
//!
//! [`macro@value`] is the one macro that is not about suppression. It states the expression
//! `cargo-gamma` substitutes for a function's body when it mutates the value that function
//! returns, in place of the one it would otherwise guess from the return type:
//!
//! ```rust
//! # trait Reader { fn read(&self) -> u8; }
//! # struct File;
//! # impl Reader for File { fn read(&self) -> u8 { 0 } }
//! // The tool cannot name a value of `dyn Reader`, so without this the site is never mutated and
//! // nothing ever asks whether the returned reader is checked.
//! #[gamma::value(Box::new(File))]
//! fn reader() -> Box<dyn Reader> {
//!     Box::new(File)
//! }
//!
//! // Here it replaces a guess rather than creating a mutant that did not exist.
//! #[gamma::value(u32::MAX)]
//! fn budget() -> u32 {
//!     512
//! }
//! ```
//!
//! It takes one expression rather than selectors, and it can only ever *add* a mutant or change
//! what an existing one substitutes — it is not a suppression channel, and the site it is written
//! on keeps being mutated whether the stated value compiles or not. A value that does not
//! type-check becomes an unviable mutant and is withdrawn on the round that discovers it, exactly
//! as a bad guess would have been.
//!
//! Write exactly one, directly on the function or method it applies to. Two on the same item is a
//! compile error rather than a rule about which one wins, and it is not inherited from an `impl`
//! block or a module, because one expression essentially never type-checks as the body of every
//! function beneath one.
//!
//! ```compile_fail
//! // Two stated values, which would otherwise leave the answer to expansion order.
//! #[gamma::value(0)]
//! #[gamma::value(1)]
//! fn budget() -> u32 {
//!     512
//! }
//! ```
//!
//! # Where they can go
//!
//! The suppression macros go on any item, and cover everything beneath it — so an attribute on a
//! module covers the module, and one on an `impl` covers every method in it:
//!
//! ```rust
//! #[gamma::skip(arith, reason = "generated fixed-point tables")]
//! mod tables {
//!     pub fn scale(x: i64) -> i64 {
//!         x * 4096
//!     }
//! }
//!
//! struct Cursor {
//!     at: usize,
//! }
//!
//! #[gamma::skip(reason = "exercised only through the fuzzer")]
//! impl Cursor {
//!     fn advance(&mut self) {
//!         self.at += 1;
//!     }
//!
//!     fn at_start(&self) -> bool {
//!         self.at == 0
//!     }
//! }
//! ```
//!
//! [`macro@value`] is the exception, and deliberately so: it goes on a function or a method and
//! nowhere else, because the expression it states has to type-check as that one signature's body.
//!
//! # Relationship to the comment form
//!
//! Attributes in statement and expression position are still unstable, so the primary channel for
//! surgical suppression is a comment that is *character-for-character* the attribute form:
//!
//! ```text
//! // #[gamma::skip(arith)]
//! let total = a * scale + offset;
//! ```
//!
//! When expression attributes stabilize, deleting the two slashes turns every such comment into
//! real Rust. This crate is what those comments become.
//!
//! The comment form takes exactly the same arguments, so nothing has to be relearned to move from
//! one to the other:
//!
//! ```text
//! // #[gamma::skip(relational, reason = "the bound is checked one frame later")]
//! if index < self.len {
//!     // #[gamma::skip(stmt, tag = "telemetry")]
//!     self.hits += 1;
//! }
//!
//! // #[gamma::expect_killed(@boundary)]
//! let clamped = value.min(limit);
//! ```
//!
//! The comment form is not validated by the compiler, since it is a comment — `cargo-gamma`
//! diagnoses a misspelled selector there instead, and refuses to treat an unrecognized directive
//! as a suppression that quietly did nothing.
//!
//! Choose the attribute when the unit being excused is a whole item, and the comment when it is one
//! statement or one expression inside an item that is otherwise worth mutating. A third channel,
//! `gamma.toml`, is the right place for a policy that is about the project rather than about
//! any particular line.

#![cfg_attr(coverage_nightly, feature(coverage_attribute))]
// Nothing in this crate can be reached by a coverage run, or killed by a mutation run. Its only
// caller is `rustc`, during the expansion of some *other* crate: the counters a proc macro increments
// inside the compiler are never written to a profile the harness collects, and a mutation run has
// finished building long before it selects a mutant, so no mutant of this code is ever active while
// a test is watching.
//
// That is why the substance lives in `cargo-gamma-attrs-impl`, an ordinary library that ordinary
// tests can call. What is left here is a shim thin enough to read at a glance, and marking it off
// is the difference between an honest 100% and a figure with an unexplained hole in it.
#![cfg_attr(coverage_nightly, coverage(off))]
// A proc-macro crate's exported functions are `TokenStream -> TokenStream`; documenting each
// individually would be noise given the crate-level docs above.
#![allow(clippy::missing_const_for_fn, reason = "proc-macro entry points cannot be const")]

use proc_macro::TokenStream;

/// Suppresses mutations on the annotated item and everything beneath it.
///
/// With no arguments, every mutator is suppressed. With arguments, only the listed selectors are:
/// a mutator name (`arith.add_to_sub`), a family prefix (`arith`), a profile (`@removal`), or an
/// academic alias (`ROR`).
///
/// # Examples
///
/// ```rust
/// // Nothing in here is mutated at all.
/// #[gamma::skip]
/// fn hand_verified(x: u32) -> u32 {
///     x + 1
/// }
///
/// // Only arithmetic is left alone; the relational mutants on `>` are still generated.
/// #[gamma::skip(arith, reason = "fixed-point, covered by proptest")]
/// fn positive_scaled(a: i64, b: i64) -> bool {
///     a * b / 1000 > 0
/// }
///
/// // A profile, minus one member, with a tag for auditing.
/// #[gamma::skip(@arithmetic, !arith.add_to_sub, tag = "hot-loop")]
/// fn blend(a: i32, b: i32) -> i32 {
///     a * b + (a - b)
/// }
/// ```
#[proc_macro_attribute]
pub fn skip(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert("skip", attr.into(), item.into()).into()
}

/// Asserts that the selected mutants *survive*, and fails the run if any is killed.
///
/// This is a ratchet for known gaps: it records the gap so that closing it is a deliberate,
/// visible act rather than an accident. Unlike [`macro@skip`], the mutants are still generated and
/// still tested — what changes is which outcome is treated as a failure.
///
/// # Examples
///
/// ```rust
/// // Nobody asserts on this text today. When somebody starts to, the run fails until this
/// // attribute is deleted, so the record never outlives the gap it describes.
/// #[gamma::expect_survived(literal, reason = "log text is deliberately not asserted on")]
/// fn describe(n: usize) -> String {
///     format!("processed {n} items")
/// }
/// ```
#[proc_macro_attribute]
pub fn expect_survived(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert("expect_survived", attr.into(), item.into()).into()
}

/// Asserts that the selected mutants are *killed*, and fails the run if any survives.
///
/// This pins a guarantee. A refactor that quietly weakens the suite fails the run at the line that
/// lost its cover, rather than showing up later as a slow drift in the overall score.
///
/// # Examples
///
/// ```rust
/// // Every mutant of this function must be caught by some test.
/// #[gamma::expect_killed]
/// fn checksum(bytes: &[u8]) -> u32 {
///     bytes.iter().fold(0u32, |acc, b| {
///         acc.wrapping_mul(31).wrapping_add(u32::from(*b))
///     })
/// }
///
/// // Or just the boundary ones, because those are what the boundary tests exist for.
/// #[gamma::expect_killed(@boundary, reason = "guarded by the range tests")]
/// fn in_range(x: i32, low: i32, high: i32) -> bool {
///     x >= low && x <= high
/// }
/// ```
#[proc_macro_attribute]
pub fn expect_killed(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert("expect_killed", attr.into(), item.into()).into()
}

/// States the expression a function's return-value mutant substitutes for its body.
///
/// `cargo-gamma` reads return types syntactically, so it guesses. Where the guess is wrong the
/// mutant does not compile and is withdrawn, and where no guess could hold — a bare type parameter,
/// an associated type, a `Box<dyn Trait>`, a non-iterator `impl Trait` — no mutant is offered at
/// all and the site goes unmeasured. This says what to substitute, which replaces the guess in the
/// first case and creates the mutant in the second.
///
/// Write exactly one, directly on the function or method whose value it states. It is not inherited
/// from an `impl` block or a module, and stating one on either is a compile error: a single
/// expression essentially never type-checks as the body of every function beneath it. For the same
/// reason it cannot be stated on a trait method that is only declared — there is no body to replace,
/// and the implementations do not inherit it. `const fn` bodies and empty bodies are never mutated,
/// so a value stated on one is honoured by nothing.
///
/// Nothing is taken on trust. The stated expression becomes an ordinary mutant, and if it does not
/// type-check it is withdrawn exactly as any other unviable mutant is — one rollback round, no
/// special handling, and never a suppression. That is what makes this the safest hint there is: the
/// compiler checks it.
///
/// # Examples
///
/// ```rust
/// # trait Reader { fn read(&self) -> u8; }
/// # struct File;
/// # impl Reader for File { fn read(&self) -> u8 { 0 } }
/// // No guess could hold here: `dyn Reader` names a capability, not a type with a `Default`, so
/// // without this the site is never mutated at all.
/// #[gamma::value(Box::new(File))]
/// fn reader() -> Box<dyn Reader> {
///     Box::new(File)
/// }
///
/// // A stated value replaces what the tool would have guessed for the return type.
/// #[gamma::value(u32::MAX)]
/// fn budget() -> u32 {
///     512
/// }
/// ```
///
/// These fail to compile, which is the point of validating the argument here rather than leaving a
/// malformed hint to be quietly ignored by the tool:
///
/// ```compile_fail
/// // Nothing is stated.
/// #[gamma::value()]
/// fn budget() -> u32 {
///     512
/// }
/// ```
///
/// ```compile_fail
/// // Two expressions; a site states one value.
/// #[gamma::value(0, 1)]
/// fn budget() -> u32 {
///     512
/// }
/// ```
///
/// ```compile_fail
/// // Not an expression at all.
/// #[gamma::value(1 +)]
/// fn budget() -> u32 {
///     512
/// }
/// ```
///
/// ```compile_fail
/// // Two stated values, which would leave the answer to expansion order.
/// #[gamma::value(0)]
/// #[gamma::value(1)]
/// fn budget() -> u32 {
///     512
/// }
/// ```
///
/// ```compile_fail
/// // An `impl` block cannot state one value for every method in it.
/// struct Cursor { at: usize }
///
/// #[gamma::value(0)]
/// impl Cursor {
///     fn at(&self) -> usize {
///         self.at
///     }
/// }
/// ```
///
/// ```compile_fail
/// // A declaration has no body to replace, and its implementations do not inherit the value.
/// trait Cursor {
///     #[gamma::value(0)]
///     fn at(&self) -> usize;
/// }
/// ```
#[proc_macro_attribute]
pub fn value(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::value(attr.into(), item.into()).into()
}

/// Sets or overrides the timeout multiplier for test execution of mutants in the annotated item.
///
/// When a mutant in the annotated item is tested, the timeout multiplier specified here overrides
/// the project default from `gamma.toml` or the `--test-timeout-multiplier` command-line argument.
///
/// # Examples
///
/// ```rust
/// // Gives mutants in this slow or variable test target 3x the baseline timeout.
/// #[gamma::test_timeout_multiplier(3.0)]
/// fn heavy_computation(data: &[u8]) -> Vec<u8> {
///     data.iter().map(|b| b.wrapping_add(1)).collect()
/// }
///
/// // Named form with reasons or specific mutators.
/// #[gamma::test_timeout_multiplier(arith, test_timeout_multiplier = 2.5, reason = "complex math")]
/// fn compute_hash(seed: u64) -> u64 {
///     seed.wrapping_mul(6364136223846793005).wrapping_add(1)
/// }
/// ```
///
/// A malformed multiplier is a compile error, so a mistyped budget fails loudly at build time
/// rather than being quietly rejected later by the tool's directive scanner — or worse, reaching
/// `Duration::mul_f64` unbounded. As with the suppression and value macros, these examples are
/// compiled and required to *fail*: only compiling one proves the failure reaches a user's build.
///
/// ```compile_fail
/// // Not a number at all.
/// #[gamma::test_timeout_multiplier("fast")]
/// fn heavy(data: &[u8]) -> usize {
///     data.len()
/// }
/// ```
///
/// ```compile_fail
/// // `inf` parses as a float but is not finite, so it can never bound a timeout. It arrives as an
/// // identifier rather than a literal, which is exactly the case a weaker guard lets through.
/// #[gamma::test_timeout_multiplier(inf)]
/// fn heavy(data: &[u8]) -> usize {
///     data.len()
/// }
/// ```
///
/// ```compile_fail
/// // Negative, so smaller than any baseline it would scale.
/// #[gamma::test_timeout_multiplier(-1.0)]
/// fn heavy(data: &[u8]) -> usize {
///     data.len()
/// }
/// ```
#[proc_macro_attribute]
pub fn test_timeout_multiplier(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert_timeout("test_timeout_multiplier", &attr.into(), item.into()).into()
}

/// Alias for [`macro@test_timeout_multiplier`].
#[proc_macro_attribute]
pub fn timeout_multiplier(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert_timeout("timeout_multiplier", &attr.into(), item.into()).into()
}

/// Generic `gamma` attribute for mutant control, including timeout multiplier overrides.
///
/// # Examples
///
/// ```rust
/// use gamma::gamma;
///
/// #[gamma(test_timeout_multiplier = 2.5)]
/// fn slow_algorithm(n: usize) -> usize {
///     n * 2
/// }
/// ```
#[proc_macro_attribute]
pub fn gamma(attr: TokenStream, item: TokenStream) -> TokenStream {
    cargo_gamma_attrs_impl::inert_timeout("gamma", &attr.into(), item.into()).into()
}
