# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# Owned by cargo-ox-check-update; edit via `cargo ox-check-update`.
name: ox-check-scheduled

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ox-check-scheduled:
    uses: ./.github/workflows/ox-check-scheduled-impl.yml
    permissions:
      contents: read
    secrets: inherit
