// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#![cfg(not(miri))] // miri can't sandbox the FS ops these tests do (TempDir, run_update).
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "panic-on-failure idioms are appropriate in tests"
)]
#![expect(clippy::unwrap_used, reason = "integration tests favor concise assertions over Result plumbing")]
#![expect(
    clippy::panic,
    reason = "integration tests panic on unmet preconditions for readable failure output"
)]

//! Consumer-upgrade coverage for the container backend replacement.
//!
//! The snapshot tests describe a fresh tree: the end state of a generation that
//! starts from nothing. This exercises the path an existing adopter takes --
//! a repository generated by 0.4.0, holding a `.anvil.lock` that tracks the
//! runner seam and its assets, updated by a binary that emits neither.
//!
//! The transition is the largest this crate has shipped: `Containerfile` and
//! its ignore file, `README.md`, `entrypoint.sh`, `image-id.{sh,ps1}` and
//! `run-in-container.{sh,ps1}` all disappear from `.anvil/container/`,
//! `justfiles/anvil/runner.just` disappears with them, and the root `Justfile`
//! loses its `anvil-runner` region. What matters is that an untouched asset is
//! removed cleanly and an *edited* one is handed back to the repository rather
//! than deleted.

use std::path::Path;

use cargo_anvil::test_support::{Cli, Decision, Manifest, RegionKey, RunOutcome, Target, checksum_str, run_update};
use cargo_anvil::{Catalog, artifacts};
use tempfile::TempDir;

/// Generated container assets that 0.4.0 tracked and this release does not.
/// Paths are as 0.4.0 wrote them.
const RETIRED_ASSETS: [&str; 8] = [
    ".anvil/container/Containerfile",
    ".anvil/container/Containerfile.dockerignore",
    ".anvil/container/README.md",
    ".anvil/container/entrypoint.sh",
    ".anvil/container/image-id.ps1",
    ".anvil/container/image-id.sh",
    ".anvil/container/run-in-container.ps1",
    ".anvil/container/run-in-container.sh",
];

/// The routing seam's own recipe file, retired with the assets above.
const RETIRED_RECIPE: &str = "justfiles/anvil/runner.just";

/// The managed region 0.4.0 spliced into the root `Justfile` to carry the
/// runner selection, and the id it was keyed by.
const RETIRED_REGION_ID: &str = "anvil-runner";
const RETIRED_REGION_BODY: &str = "anvil_runner := \"native\"\n";

fn write(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    std::fs::write(path, contents).unwrap();
}

fn workspace() -> TempDir {
    let tmp = TempDir::new().unwrap();
    let root = tmp.path();
    write(
        &root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/*\"]\n",
    );
    write(
        &root.join("crates/alpha/Cargo.toml"),
        "[package]\nname = \"alpha\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    );
    write(&root.join("crates/alpha/src/lib.rs"), "");
    tmp
}

fn local() -> Cli {
    Cli {
        backends: vec![],
        no_backends: true,
        dry_run: false,
        force: false,
    }
}

/// Rewrite a freshly generated tree into the shape 0.4.0 produced: the retired
/// assets present on disk and tracked in the lock, and none of this release's
/// container artifacts present at all.
///
/// The checksum recorded for each retired asset is the checksum of the body
/// written here, which is what makes the file "untouched since last render" and
/// so eligible for `Remove`. A test that wants the customized path overwrites
/// the body afterwards, leaving the recorded checksum stale on purpose.
fn rewind_to_runner_layout(root: &Path) -> Manifest {
    let mut manifest = Manifest::load(root).unwrap();

    for artifact in artifacts::container::all() {
        let path = match artifact {
            cargo_anvil::Artifact::OwnedFile(spec) => spec.path,
            cargo_anvil::Artifact::Region(_) => panic!("container artifacts are owned files"),
        };
        let full = root.join(path);
        if full.exists() {
            std::fs::remove_file(&full).unwrap();
        }
        manifest.files.remove(path);
    }

    for path in RETIRED_ASSETS.iter().copied().chain(std::iter::once(RETIRED_RECIPE)) {
        let body = format!("# 0.4.0 generated {path}\n");
        write(&root.join(path), &body);
        manifest.files.insert(path.to_owned(), checksum_str(&body));
    }

    // The managed region 0.4.0 spliced into the root Justfile. Seeding it is
    // what makes the removal assertion mean anything: without it the Justfile
    // never contained `anvil-runner`, so asserting its absence afterwards would
    // hold before the upgrade ran and would keep holding if region removal
    // broke entirely.
    let justfile_path = root.join("Justfile");
    let justfile = std::fs::read_to_string(&justfile_path).unwrap();
    let region = format!("# >>> anvil-managed: {RETIRED_REGION_ID}\n{RETIRED_REGION_BODY}# <<< anvil-managed: {RETIRED_REGION_ID}\n");
    write(&justfile_path, &format!("{justfile}\n{region}"));
    manifest.regions.insert(
        RegionKey {
            host: "Justfile".to_owned(),
            id: RETIRED_REGION_ID.to_owned(),
        },
        checksum_str(RETIRED_REGION_BODY),
    );

    // Provenance of the older build. Recorded, never a gate.
    manifest.catalog_checksum = Some("sha256:0000000000000000000000000000000000000000000000000000000000000000".to_owned());
    manifest.tool_version = Some("0.4.0".to_owned());
    manifest.save(root).unwrap();
    manifest
}

fn decision_for(outcome: &RunOutcome, path: &str) -> Decision {
    outcome
        .plan
        .items()
        .iter()
        .find(|item| matches!(&item.target, Target::File { path: candidate } if candidate == path))
        .unwrap_or_else(|| panic!("no plan item for {path}"))
        .decision
}

#[test]
fn upgrading_from_the_runner_layout_retires_the_seam_and_emits_the_new_backend() {
    let tmp = workspace();
    let root = tmp.path();
    run_update(&Catalog::anvil(), &local(), root).unwrap();
    rewind_to_runner_layout(root);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();
    assert!(outcome.applied);
    let manifest = Manifest::load(root).unwrap();

    // Untouched retired assets are deleted and untracked. Leaving them behind
    // would ship a repository two container backends, one of which no recipe
    // can reach.
    for path in RETIRED_ASSETS.iter().copied().chain(std::iter::once(RETIRED_RECIPE)) {
        assert_eq!(decision_for(&outcome, path), Decision::Remove, "{path} must be removed");
        assert!(!root.join(path).exists(), "{path} must be gone from disk");
        assert!(!manifest.files.contains_key(path), "{path} must be dropped from the lock");
    }

    // This release's artifacts take their place and are tracked.
    for artifact in artifacts::container::all() {
        let path = match artifact {
            cargo_anvil::Artifact::OwnedFile(spec) => spec.path,
            cargo_anvil::Artifact::Region(_) => panic!("container artifacts are owned files"),
        };
        assert!(root.join(path).is_file(), "{path} must be written");
        assert!(manifest.files.contains_key(path), "{path} must be tracked");
    }

    // The runner region is spliced out of the root Justfile, and nothing else
    // is: the surrounding content the repository owns must survive intact.
    // Seeded in the rewind above, so this assertion can actually fail.
    let region_decision = outcome
        .plan
        .items()
        .iter()
        .find(|item| matches!(&item.target, Target::Region { host, id } if host == "Justfile" && id == RETIRED_REGION_ID))
        .map(|item| item.decision);
    assert_eq!(
        region_decision,
        Some(Decision::Remove),
        "the obsolete runner region must be planned for removal"
    );

    let justfile = std::fs::read_to_string(root.join("Justfile")).unwrap();
    assert!(!justfile.contains(RETIRED_REGION_ID), "the runner region must be spliced out");
    assert!(!justfile.contains(RETIRED_REGION_BODY.trim()), "the region body must go with it");
    assert!(justfile.contains("anvil"), "the Justfile must still import the anvil tree");
    assert!(
        !Manifest::load(root).unwrap().regions.keys().any(|key| key.id == RETIRED_REGION_ID),
        "the region must be dropped from the lock"
    );
}

#[test]
fn an_edited_retired_asset_is_handed_back_rather_than_deleted() {
    let tmp = workspace();
    let root = tmp.path();
    run_update(&Catalog::anvil(), &local(), root).unwrap();
    rewind_to_runner_layout(root);

    // The adopter patched their Containerfile. The lock still holds the
    // checksum of the generated body, so anvil can see the divergence.
    let edited = ".anvil/container/Containerfile";
    let body = "FROM ubuntu:24.04\n# locally patched base\n";
    write(&root.join(edited), body);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();
    assert!(outcome.applied);

    // Removing a file the repository has edited would destroy work anvil did
    // not author. Ownership transfers instead: the file stays, the lock entry
    // goes.
    assert_eq!(
        decision_for(&outcome, edited),
        Decision::OrphanedKept,
        "an edited retired asset must be kept"
    );
    assert_eq!(
        std::fs::read_to_string(root.join(edited)).unwrap(),
        body,
        "the adopter's content must be preserved byte for byte"
    );
    assert!(
        !Manifest::load(root).unwrap().files.contains_key(edited),
        "the lock entry must be dropped so the file becomes the repository's"
    );
}
