// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#![cfg(not(miri))] // miri can't sandbox the FS ops these tests do (TempDir, run_update).
#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "panic-on-failure idioms are appropriate in tests"
)]
#![expect(clippy::unwrap_used, reason = "integration tests favor concise assertions over Result plumbing")]
#![expect(
    clippy::panic,
    reason = "integration tests panic on unmet preconditions for readable failure output"
)]

//! Consumer-upgrade coverage for the container backend replacement.
//!
//! The snapshot tests describe a fresh tree: the end state of a generation that
//! starts from nothing. This exercises the path an existing adopter takes --
//! a repository generated by 0.4.0, holding a `.anvil.lock` that tracks the
//! runner seam and its assets, updated by a binary that emits neither.
//!
//! The transition is the largest this crate has shipped: `Containerfile` and
//! its ignore file, `README.md`, `entrypoint.sh`, `image-id.{sh,ps1}` and
//! `run-in-container.{sh,ps1}` all disappear from `.anvil/container/`,
//! `justfiles/anvil/runner.just` disappears with them, and the root `Justfile`
//! loses its `anvil-runner` region. What matters is that an untouched asset is
//! removed cleanly and an *edited* one is handed back to the repository rather
//! than deleted.

use std::path::Path;

use cargo_anvil::test_support::{Cli, Decision, Manifest, RegionKey, RunOutcome, Target, checksum_str, run_update};
use cargo_anvil::{Catalog, artifacts};
use tempfile::TempDir;

/// Generated container assets that 0.4.0 tracked and this release does not.
/// Paths are as 0.4.0 wrote them.
const RETIRED_ASSETS: [&str; 8] = [
    ".anvil/container/Containerfile",
    ".anvil/container/Containerfile.dockerignore",
    ".anvil/container/README.md",
    ".anvil/container/entrypoint.sh",
    ".anvil/container/image-id.ps1",
    ".anvil/container/image-id.sh",
    ".anvil/container/run-in-container.ps1",
    ".anvil/container/run-in-container.sh",
];

/// The routing seam's own recipe file, retired with the assets above.
const RETIRED_RECIPE: &str = "justfiles/anvil/runner.just";

/// The managed region 0.4.0 spliced into the root `Justfile` to carry the
/// runner selection, and the id it was keyed by.
const RETIRED_REGION_ID: &str = "anvil-runner";
const RETIRED_REGION_BODY: &str = "anvil_runner := \"native\"\n";

fn write(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    std::fs::write(path, contents).unwrap();
}

fn workspace() -> TempDir {
    let tmp = TempDir::new().unwrap();
    let root = tmp.path();
    write(
        &root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/*\"]\n",
    );
    write(
        &root.join("crates/alpha/Cargo.toml"),
        "[package]\nname = \"alpha\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    );
    write(&root.join("crates/alpha/src/lib.rs"), "");
    tmp
}

fn local() -> Cli {
    Cli {
        backends: vec![],
        no_backends: true,
        dry_run: false,
        force: false,
    }
}

/// A workspace that has already been generated once, so the lock and the
/// composed tree exist and a test can rewind one part of them.
fn generated_tree() -> TempDir {
    let tmp = workspace();
    run_update(&Catalog::anvil(), &local(), tmp.path()).unwrap();
    tmp
}

/// Rewrite a freshly generated tree into the shape 0.4.0 produced: the retired
/// assets present on disk and tracked in the lock, and none of this release's
/// container artifacts present at all.
///
/// The checksum recorded for each retired asset is the checksum of the body
/// written here, which is what makes the file "untouched since last render" and
/// so eligible for `Remove`. A test that wants the customized path overwrites
/// the body afterwards, leaving the recorded checksum stale on purpose.
fn rewind_to_runner_layout(root: &Path) -> Manifest {
    let mut manifest = Manifest::load(root).unwrap();

    for artifact in artifacts::container::all() {
        // The Dockerfile is composed now, so the group is a mix: the recipe and
        // the ignore file are owned, the image definition is four regions in a
        // host this rewind deletes outright.
        let path = match artifact {
            cargo_anvil::Artifact::OwnedFile(spec) => spec.path,
            cargo_anvil::Artifact::Region(_) => continue,
        };
        let full = root.join(path);
        if full.exists() {
            std::fs::remove_file(&full).unwrap();
        }
        manifest.files.remove(path);
    }

    let dockerfile = root.join(".anvil/container/Dockerfile");
    if dockerfile.exists() {
        std::fs::remove_file(&dockerfile).unwrap();
    }
    manifest
        .regions
        .retain(|key, _| !key.host.starts_with(".anvil/container/Dockerfile"));

    for path in RETIRED_ASSETS.iter().copied().chain(std::iter::once(RETIRED_RECIPE)) {
        let body = format!("# 0.4.0 generated {path}\n");
        write(&root.join(path), &body);
        manifest.files.insert(path.to_owned(), checksum_str(&body));
    }

    // The managed region 0.4.0 spliced into the root Justfile. Seeding it is
    // what makes the removal assertion mean anything: without it the Justfile
    // never contained `anvil-runner`, so asserting its absence afterwards would
    // hold before the upgrade ran and would keep holding if region removal
    // broke entirely.
    let justfile_path = root.join("Justfile");
    let justfile = std::fs::read_to_string(&justfile_path).unwrap();
    let region = format!("# >>> anvil-managed: {RETIRED_REGION_ID}\n{RETIRED_REGION_BODY}# <<< anvil-managed: {RETIRED_REGION_ID}\n");
    write(&justfile_path, &format!("{justfile}\n{region}"));
    manifest.regions.insert(
        RegionKey {
            host: "Justfile".to_owned(),
            id: RETIRED_REGION_ID.to_owned(),
        },
        checksum_str(RETIRED_REGION_BODY),
    );

    // Provenance of the older build. Recorded, never a gate.
    manifest.catalog_checksum = Some("sha256:0000000000000000000000000000000000000000000000000000000000000000".to_owned());
    manifest.tool_version = Some("0.4.0".to_owned());
    manifest.save(root).unwrap();
    manifest
}

fn decision_for(outcome: &RunOutcome, path: &str) -> Decision {
    outcome
        .plan
        .items()
        .iter()
        .find(|item| matches!(&item.target, Target::File { path: candidate } if candidate == path))
        .unwrap_or_else(|| panic!("no plan item for {path}"))
        .decision
}

#[test]
fn upgrading_from_the_runner_layout_retires_the_seam_and_emits_the_new_backend() {
    let tmp = workspace();
    let root = tmp.path();
    run_update(&Catalog::anvil(), &local(), root).unwrap();
    rewind_to_runner_layout(root);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();
    assert!(outcome.applied);
    let manifest = Manifest::load(root).unwrap();

    // Untouched retired assets are deleted and untracked. Leaving them behind
    // would ship a repository two container backends, one of which no recipe
    // can reach.
    for path in RETIRED_ASSETS.iter().copied().chain(std::iter::once(RETIRED_RECIPE)) {
        assert_eq!(decision_for(&outcome, path), Decision::Remove, "{path} must be removed");
        assert!(!root.join(path).exists(), "{path} must be gone from disk");
        assert!(!manifest.files.contains_key(path), "{path} must be dropped from the lock");
    }

    // This release's artifacts take their place and are tracked.
    for artifact in artifacts::container::all() {
        match artifact {
            cargo_anvil::Artifact::OwnedFile(spec) => {
                assert!(root.join(spec.path).is_file(), "{} must be written", spec.path);
                assert!(manifest.files.contains_key(spec.path), "{} must be tracked", spec.path);
            }
            cargo_anvil::Artifact::Region(spec) => {
                let cargo_anvil::HostSelector::Path(host) = &spec.host else {
                    panic!("container regions target a literal path");
                };
                let composed = std::fs::read_to_string(root.join(host)).unwrap();
                assert!(
                    composed.contains(&format!("# >>> anvil-managed: {}", spec.id)),
                    "{} must be spliced into {host}",
                    spec.id
                );
                assert!(
                    manifest.regions.contains_key(&RegionKey {
                        host: host.clone(),
                        id: spec.id.as_str().to_owned(),
                    }),
                    "{} must be tracked",
                    spec.id
                );
            }
        }
    }

    // The composed Dockerfile keeps its seeded parser directive on line 1:
    // BuildKit honors it nowhere else, and a region sentinel above it would
    // demote it silently.
    let dockerfile = std::fs::read_to_string(root.join(".anvil/container/Dockerfile")).unwrap();
    assert!(
        dockerfile.starts_with("# syntax=docker/dockerfile:1\n"),
        "the composed Dockerfile must lead with the parser directive"
    );

    // The runner region is spliced out of the root Justfile, and nothing else
    // is: the surrounding content the repository owns must survive intact.
    // Seeded in the rewind above, so this assertion can actually fail.
    let region_decision = outcome
        .plan
        .items()
        .iter()
        .find(|item| matches!(&item.target, Target::Region { host, id } if host == "Justfile" && id == RETIRED_REGION_ID))
        .map(|item| item.decision);
    assert_eq!(
        region_decision,
        Some(Decision::Remove),
        "the obsolete runner region must be planned for removal"
    );

    let justfile = std::fs::read_to_string(root.join("Justfile")).unwrap();
    assert!(!justfile.contains(RETIRED_REGION_ID), "the runner region must be spliced out");
    assert!(!justfile.contains(RETIRED_REGION_BODY.trim()), "the region body must go with it");
    assert!(justfile.contains("anvil"), "the Justfile must still import the anvil tree");
    assert!(
        !Manifest::load(root).unwrap().regions.keys().any(|key| key.id == RETIRED_REGION_ID),
        "the region must be dropped from the lock"
    );
}

#[test]
fn an_edited_retired_asset_is_handed_back_rather_than_deleted() {
    let tmp = workspace();
    let root = tmp.path();
    run_update(&Catalog::anvil(), &local(), root).unwrap();
    rewind_to_runner_layout(root);

    // The adopter patched their Containerfile. The lock still holds the
    // checksum of the generated body, so anvil can see the divergence.
    let edited = ".anvil/container/Containerfile";
    let body = "FROM ubuntu:24.04\n# locally patched base\n";
    write(&root.join(edited), body);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();
    assert!(outcome.applied);

    // Removing a file the repository has edited would destroy work anvil did
    // not author. Ownership transfers instead: the file stays, the lock entry
    // goes.
    assert_eq!(
        decision_for(&outcome, edited),
        Decision::OrphanedKept,
        "an edited retired asset must be kept"
    );
    assert_eq!(
        std::fs::read_to_string(root.join(edited)).unwrap(),
        body,
        "the adopter's content must be preserved byte for byte"
    );
    assert!(
        !Manifest::load(root).unwrap().files.contains_key(edited),
        "the lock entry must be dropped so the file becomes the repository's"
    );
}

/// The release before this one owned `.anvil/container/Dockerfile` outright: a
/// single generated file a repository was invited to edit in place. This
/// release composes the same path from four managed regions.
///
/// The upgrade must replace that file, not append to it. Appending would leave
/// the whole previous definition above the regions -- a second `FROM`, a second
/// set of pins, and an image built from whichever the frontend saw first.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn upgrading_from_the_owned_dockerfile_reseeds_the_composed_host() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // Rewind to the owned-file shape: one generated file, tracked in the lock
    // by the checksum of exactly what is on disk, and no regions recorded.
    let previous_render =
        "# syntax=docker/dockerfile:1\n# Managed by cargo-anvil.\nFROM docker.io/library/ubuntu:24.04\nRUN apt-get update\n";
    write(&dockerfile, previous_render);
    let mut manifest = Manifest::load(root).unwrap();
    manifest
        .files
        .insert(".anvil/container/Dockerfile".to_owned(), checksum_str(previous_render));
    manifest.regions.retain(|key, _| key.host != ".anvil/container/Dockerfile");
    manifest.save(root).unwrap();

    run_update(&Catalog::anvil(), &local(), root).unwrap();

    let composed = std::fs::read_to_string(&dockerfile).unwrap();
    assert_eq!(
        composed.matches("\nFROM ").count() + usize::from(composed.starts_with("FROM ")),
        1,
        "the superseded definition must be replaced, not appended to:\n{composed}"
    );
    assert!(
        !composed.contains("RUN apt-get update\n# >>>"),
        "no line of the previous render may survive above the regions"
    );
    assert!(composed.starts_with("# syntax=docker/dockerfile:1\n"));
    for id in [
        "anvil-container-base",
        "anvil-container-tools",
        "anvil-container-setup",
        "anvil-container-entry",
    ] {
        assert!(composed.contains(&format!("# >>> anvil-managed: {id}")), "{id} must be spliced in");
    }

    // The stale owned-file entry is gone; the regions are tracked in its place.
    let after = Manifest::load(root).unwrap();
    assert!(
        !after.files.contains_key(".anvil/container/Dockerfile"),
        "the superseded owned-file entry must be dropped from the lock"
    );
    assert!(
        after.regions.contains_key(&RegionKey {
            host: ".anvil/container/Dockerfile".to_owned(),
            id: "anvil-container-base".to_owned(),
        }),
        "the composed regions must be tracked instead"
    );
}

/// A Dockerfile the repository wrote itself -- never tracked as an owned file --
/// cannot be composed by appending regions to it: everything already in the file
/// would end up above `FROM`. Anvil must refuse and say so, leaving the file
/// untouched, rather than writing something that cannot build.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_repository_authored_dockerfile_is_refused_not_appended_to() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    let hand_written = "# hand written by the repository\nRUN echo mine\n";
    write(&dockerfile, hand_written);
    let mut manifest = Manifest::load(root).unwrap();
    manifest.files.remove(".anvil/container/Dockerfile");
    manifest.regions.retain(|key, _| key.host != ".anvil/container/Dockerfile");
    manifest.save(root).unwrap();

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    assert_eq!(
        std::fs::read_to_string(&dockerfile).unwrap(),
        hand_written,
        "content anvil never owned must be left exactly as found"
    );
    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.contains(".anvil/container/Dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host: {refusals:?}");
    assert!(
        refusals[0].contains("anvil has never owned it"),
        "the diagnostic must explain why it cannot be composed: {}",
        refusals[0]
    );
}

/// The upgrade re-seed replaces the previous release's whole-file render. It
/// must not do that when the repository edited that file: the file is not
/// tracked region-by-region, so there is no proposal to fall back on and
/// nothing to recover the edit from.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn an_edited_superseded_dockerfile_is_never_overwritten() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // Tracked as an owned file, but the recorded checksum is of a *different*
    // body: the repository edited it after anvil last wrote it.
    let previous_render = "# syntax=docker/dockerfile:1\nFROM docker.io/library/ubuntu:24.04\n";
    let edited = format!("{previous_render}RUN apt-get install -y our-internal-tool\n");
    write(&dockerfile, &edited);
    let mut manifest = Manifest::load(root).unwrap();
    manifest
        .files
        .insert(".anvil/container/Dockerfile".to_owned(), checksum_str(previous_render));
    manifest.regions.retain(|key, _| key.host != ".anvil/container/Dockerfile");
    manifest.save(root).unwrap();

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    assert_eq!(
        std::fs::read_to_string(&dockerfile).unwrap(),
        edited,
        "an edit made after the last render must survive the upgrade untouched"
    );
    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.contains(".anvil/container/Dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host: {refusals:?}");
    assert!(
        refusals[0].contains("edited after anvil last wrote it"),
        "the diagnostic must name the reason: {}",
        refusals[0]
    );
}

/// A half-composed file — some of anvil's regions present, others missing — is
/// what an adopter has the first time anvil adds a region to the set. That is a
/// normal upgrade: each missing region is inserted at its declared position, so
/// the file stays ordered and the repository's own content between the regions
/// survives untouched.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_newly_added_region_is_inserted_in_order_not_appended() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // Drop the base region and put repository content in the gaps around it,
    // exactly as an adopter would have. Appending the region back would land
    // `FROM` after the layers that depend on it.
    let text = std::fs::read_to_string(&dockerfile).unwrap();
    let open = text.find("# >>> anvil-managed: anvil-container-base\n").unwrap();
    let close_marker = "# <<< anvil-managed: anvil-container-base\n";
    let close = text.find(close_marker).unwrap() + close_marker.len();
    let without_base = format!("{}# MINE-BEFORE\n{}# MINE-AFTER\n", &text[..open], &text[close..]);
    write(&dockerfile, &without_base);
    let mut manifest = Manifest::load(root).unwrap();
    manifest
        .regions
        .retain(|key, _| !(key.host == ".anvil/container/Dockerfile" && key.id == "anvil-container-base"));
    manifest.save(root).unwrap();

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();
    assert!(
        outcome.plan.refusals().is_empty(),
        "adding a region is an upgrade, not a refusal: {:?}",
        outcome.plan.refusals()
    );

    let composed = std::fs::read_to_string(&dockerfile).unwrap();
    let at = |needle: &str| {
        composed
            .find(needle)
            .unwrap_or_else(|| panic!("missing from recomposed Dockerfile: {needle}\n{composed}"))
    };
    // Restored in order, not at the end.
    assert!(at("ARG BASE_IMAGE=") < at("FROM ${BASE_IMAGE}"));
    assert!(at("FROM ${BASE_IMAGE}") < at("RUN apt-get update"));
    assert!(at("RUN apt-get update") < at("WORKDIR /workspace"));
    // And the repository's own lines are still there.
    assert!(composed.contains("# MINE-BEFORE"), "gap content before the region must survive");
    assert!(composed.contains("# MINE-AFTER"), "gap content after the region must survive");
    // `# MINE-AFTER` sits in the gap that follows the restored region's
    // predecessor. The region has to land above it: inserting one line lower
    // would split the repository's gap content around anvil's sentinels.
    assert!(
        at("# >>> anvil-managed: anvil-container-base\n") < at("# MINE-AFTER"),
        "the restored region must land above the gap content, not inside it:\n{composed}"
    );
}

/// The Dockerfile is the first managed-region host whose region *order* is
/// semantic: `FROM` must precede everything, and the toolchain must exist
/// before `anvil-setup` runs. `upsert_region` replaces a region wherever it
/// finds it, so a reordered file would otherwise be updated in place into a
/// Dockerfile that is silently wrong or cannot build at all.
///
/// Anvil must refuse the host and say which region moved, exactly once, rather
/// than once per region.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_reordered_composed_dockerfile_is_refused_with_one_diagnostic() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // Move the base region below the others, which is exactly the mistake a
    // repository makes by dropping its own instructions above `FROM`.
    let text = std::fs::read_to_string(&dockerfile).unwrap();
    let open = text.find("# >>> anvil-managed: anvil-container-base\n").unwrap();
    let close_marker = "# <<< anvil-managed: anvil-container-base\n";
    let close = text.find(close_marker).unwrap() + close_marker.len();
    let base = &text[open..close];
    let reordered = format!("{}{}\n{}", &text[..open], &text[close..], base);
    write(&dockerfile, &reordered);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.contains(".anvil/container/Dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host, not one per region: {refusals:?}");
    assert!(
        refusals[0].contains("'anvil-container-tools' appears before 'anvil-container-base'"),
        "the diagnostic must name the region that moved: {}",
        refusals[0]
    );

    // Refusing means leaving the file exactly as it was found. Rewriting it
    // would destroy whatever the repository put between the regions.
    assert_eq!(
        std::fs::read_to_string(&dockerfile).unwrap(),
        reordered,
        "a refused host must not be modified"
    );
}

/// A refusal says "nothing was written to it". That has to be true of the lock
/// as well as the file: the recorded checksum is the provenance the next run
/// reclassifies from, and the clean recovery -- revert the edit, get a valid
/// re-seed -- only exists while it survives. Dropping it would make a file
/// anvil rendered look like one it has never owned, and the second run would
/// give the wrong diagnostic.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn refusing_a_composed_host_leaves_its_lock_entry_intact() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    let previous_render = "# syntax=docker/dockerfile:1\nFROM docker.io/library/ubuntu:24.04\n";
    let edited = format!("{previous_render}RUN apt-get install -y our-internal-tool\n");
    write(&dockerfile, &edited);
    let mut manifest = Manifest::load(root).unwrap();
    manifest
        .files
        .insert(".anvil/container/Dockerfile".to_owned(), checksum_str(previous_render));
    manifest.regions.retain(|key, _| key.host != ".anvil/container/Dockerfile");
    manifest.save(root).unwrap();
    let lock_before = std::fs::read_to_string(root.join(".anvil.lock")).unwrap();

    run_update(&Catalog::anvil(), &local(), root).unwrap();

    let after = Manifest::load(root).unwrap();
    assert_eq!(
        after.files.get(".anvil/container/Dockerfile"),
        Some(&checksum_str(previous_render)),
        "a refused host keeps its recorded checksum, or its provenance is gone"
    );
    assert_eq!(
        std::fs::read_to_string(root.join(".anvil.lock")).unwrap(),
        lock_before,
        "refusing must not rewrite the lock at all"
    );

    // And the recovery the message advertises still works: revert the edit and
    // the next run composes the file cleanly.
    write(&dockerfile, previous_render);
    run_update(&Catalog::anvil(), &local(), root).unwrap();
    let composed = std::fs::read_to_string(&dockerfile).unwrap();
    assert!(composed.starts_with("# syntax=docker/dockerfile:1\n"));
    for id in [
        "anvil-container-base",
        "anvil-container-tools",
        "anvil-container-setup",
        "anvil-container-entry",
    ] {
        assert!(
            composed.contains(&format!("# >>> anvil-managed: {id}")),
            "{id} must be spliced in after recovery"
        );
    }
}

/// A malformed sentinel must be reported as such, not folded in with "this
/// region is missing" -- the content is right there, with a broken marker.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_malformed_sentinel_is_named_in_the_refusal() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // Duplicate the opening sentinel, leaving the close unmatched.
    let text = std::fs::read_to_string(&dockerfile).unwrap();
    let opener = "# >>> anvil-managed: anvil-container-base";
    let broken = text.replacen(opener, &format!("{opener}\n{opener}"), 1);
    write(&dockerfile, &broken);

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    assert_eq!(
        std::fs::read_to_string(&dockerfile).unwrap(),
        broken,
        "a refused host must not be modified"
    );
    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.contains(".anvil/container/Dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host: {refusals:?}");
    assert!(
        refusals[0].contains("cannot be read"),
        "a broken sentinel must not be reported as a missing region: {}",
        refusals[0]
    );
}

/// The guard that refuses a repository-authored Dockerfile is reached through
/// a host name resolved from disk, so it must not be keyed off the canonical
/// spelling. A repository that wrote a lower-cased `dockerfile` -- the commoner
/// spelling in the wild, and indistinguishable from the canonical one on
/// Windows and macOS -- would otherwise miss the composed-host lookup entirely,
/// get no refusal, and have anvil's six regions appended below its own `FROM`.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_case_variant_repository_dockerfile_is_refused_too() {
    let tmp = generated_tree();
    let root = tmp.path();
    let canonical = root.join(".anvil/container/Dockerfile");
    let lowercased = root.join(".anvil/container/dockerfile");

    std::fs::remove_file(&canonical).unwrap();
    let hand_written = "# hand written by the repository\nFROM mine:1\nRUN echo mine\n";
    write(&lowercased, hand_written);
    let mut manifest = Manifest::load(root).unwrap();
    manifest.files.remove(".anvil/container/Dockerfile");
    manifest.regions.retain(|key, _| key.host != ".anvil/container/Dockerfile");
    manifest.save(root).unwrap();

    // Without this the test passes vacuously on a case-insensitive filesystem
    // that kept the old directory entry.
    assert_eq!(
        on_disk_dockerfile_name(root),
        "dockerfile",
        "precondition: the host is lower-cased on disk"
    );

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    assert_eq!(
        std::fs::read_to_string(&lowercased).unwrap(),
        hand_written,
        "content anvil never owned must be left exactly as found"
    );
    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.to_lowercase().contains(".anvil/container/dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host: {refusals:?}");
    assert!(
        refusals[0].contains("anvil has never owned it"),
        "the diagnostic must explain why it cannot be composed: {}",
        refusals[0]
    );
}

/// A case-only rename of an already composed host leaves the lock keyed by the
/// old spelling and the pass keyed by the new one. Nothing is missing -- every
/// region is still in the file, rewritten this pass -- so the stale entries
/// must transfer ownership rather than be treated as orphans: removing them
/// would strip the pass's own writes and leave a Dockerfile with no `FROM`.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_case_only_rename_of_a_composed_host_keeps_its_regions() {
    let tmp = generated_tree();
    let root = tmp.path();
    let canonical = root.join(".anvil/container/Dockerfile");
    let lowercased = root.join(".anvil/container/dockerfile");

    let composed = std::fs::read_to_string(&canonical).unwrap();
    let regions_before = composed.matches("# >>> anvil-managed:").count();
    assert!(regions_before >= 2, "precondition: the host is composed from several regions");
    std::fs::remove_file(&canonical).unwrap();
    write(&lowercased, &composed);
    assert_eq!(
        on_disk_dockerfile_name(root),
        "dockerfile",
        "precondition: the host is lower-cased on disk"
    );

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    let after = std::fs::read_to_string(&lowercased).unwrap();
    assert_eq!(
        after.matches("# >>> anvil-managed:").count(),
        regions_before,
        "a case-only rename must not cost the host any of its regions:\n{after}"
    );
    assert!(
        after.contains("\nFROM "),
        "the composed file must still declare a base image:\n{after}"
    );
    let removed: Vec<&Target> = outcome
        .plan
        .items()
        .iter()
        .filter(|i| i.decision == Decision::Remove)
        .map(|i| &i.target)
        .collect();
    assert!(removed.is_empty(), "nothing may be removed for a case-only rename: {removed:?}");
}

/// The real on-disk spelling of the composed host, so the case tests cannot
/// pass without the rename they claim to make having taken effect.
fn on_disk_dockerfile_name(root: &Path) -> String {
    std::fs::read_dir(root.join(".anvil/container"))
        .unwrap()
        .flatten()
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .find(|n| n.eq_ignore_ascii_case("Dockerfile"))
        .expect("the composed host must exist")
}

/// A composed host lives in `manifest.regions` and never in `manifest.files`,
/// so "no file entry" is not the same as "anvil has never seen this path". It
/// is also every composed file that has lost its regions to a merge, a revert
/// or an edit -- and the lock still records them. Reporting that as a
/// never-owned file tells the reader to delete a file anvil rendered, throwing
/// away the gap content the refusal exists to protect, when the cheap recovery
/// is restoring the file.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_composed_host_that_lost_its_regions_is_told_to_restore_it() {
    let tmp = generated_tree();
    let root = tmp.path();
    let dockerfile = root.join(".anvil/container/Dockerfile");

    // The lock is left exactly as generated: it still records every region.
    let recorded = Manifest::load(root).unwrap();
    assert!(
        recorded.regions.keys().any(|key| key.host == ".anvil/container/Dockerfile"),
        "precondition: the lock records the composed host's regions"
    );
    assert!(
        !recorded.files.contains_key(".anvil/container/Dockerfile"),
        "precondition: a composed host is never tracked as an owned file"
    );
    write(&dockerfile, "# my own content\nFROM mine:1\n");

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    let refusals: Vec<&String> = outcome
        .plan
        .refusals()
        .iter()
        .filter(|r| r.contains(".anvil/container/Dockerfile"))
        .collect();
    assert_eq!(refusals.len(), 1, "one diagnostic per host: {refusals:?}");
    assert!(
        !refusals[0].contains("anvil has never owned it"),
        "the lock records the regions, so this is not a never-owned file: {}",
        refusals[0]
    );
    assert!(
        refusals[0].contains("Restore the file"),
        "the recovery must be restoring the file, not deleting it: {}",
        refusals[0]
    );
}

/// The removal pass compares the lock's casing against the casing every plan
/// item resolved from disk. Without resolving first, a case-only rename makes
/// anvil's own artifact look retired -- and on a case-insensitive filesystem
/// the removal opens the very file the pass just wrote and deletes it.
#[cfg_attr(miri, ignore = "uses filesystem; miri isolation forbids it")]
#[test]
fn a_case_only_rename_of_an_owned_file_is_not_deleted() {
    let tmp = generated_tree();
    let root = tmp.path();
    let canonical = root.join("justfiles/anvil/tools.just");
    let renamed = root.join("justfiles/anvil/Tools.just");
    assert!(canonical.is_file(), "precondition: the owned recipe exists as generated");

    let body = std::fs::read_to_string(&canonical).unwrap();
    std::fs::remove_file(&canonical).unwrap();
    write(&renamed, &body);
    // The lock still carries the original casing, which is the whole point.
    assert_eq!(
        Manifest::load(root).unwrap().file_checksum("justfiles/anvil/tools.just"),
        Some(checksum_str(&body).as_str()),
        "precondition: the lock records the pre-rename casing"
    );

    let outcome = run_update(&Catalog::anvil(), &local(), root).unwrap();

    let removed: Vec<String> = outcome
        .plan
        .items()
        .iter()
        .filter(|i| i.decision == Decision::Remove)
        .filter_map(|i| match &i.target {
            Target::File { path } => Some(path.clone()),
            Target::Region { .. } => None,
        })
        .collect();
    assert!(
        !removed.iter().any(|p| p.eq_ignore_ascii_case("justfiles/anvil/tools.just")),
        "anvil must not retire the artifact it just wrote: {removed:?}"
    );
    assert!(
        renamed.is_file() || canonical.is_file(),
        "the generated recipe must still be on disk after the run"
    );
    assert!(
        !root.join("justfiles/anvil/Tools.just.anvil-proposed").exists()
            && !root.join("justfiles/anvil/tools.just.anvil-proposed").exists(),
        "a file anvil still owns must not be proposed against as though it were repository-authored"
    );
}
