# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.

param(
    [switch] $ValidateWorkspaceMsrv,
    [switch] $InstallIfMissing,
    [switch] $ForEnvironment
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3

$repoRoot = Split-Path -Parent $PSScriptRoot

function Get-SelectingToolchainFile {
    foreach ($name in @('rust-toolchain', 'rust-toolchain.toml')) {
        $path = Join-Path $repoRoot $name
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            continue
        }

        $content = Get-Content -LiteralPath $path -Raw
        if ($name -eq 'rust-toolchain' -and $content.TrimStart() -notmatch '^\[') {
            return [pscustomobject]@{ Path = $path; Value = $content.Trim(); Source = 'file'; Installable = $false }
        }

        $inToolchain = $false
        foreach ($line in $content -split '\r?\n') {
            if ($line -match '^\s*\[\s*toolchain\s*\]\s*(?:#.*)?$') {
                $inToolchain = $true
                continue
            }
            if ($line -match '^\s*\[') {
                $inToolchain = $false
                continue
            }
            if ($inToolchain -and $line -match '^\s*["'']?(channel|path)["'']?\s*=\s*(["''])([^"'']+)\2\s*(?:#.*)?$') {
                $value = $Matches[3]
                if ($Matches[1] -eq 'path' -and -not [IO.Path]::IsPathRooted($value)) {
                    $value = [IO.Path]::GetFullPath((Join-Path $repoRoot $value))
                }
                return [pscustomobject]@{
                    Path = $path
                    Value = $value
                    Source = 'file'
                    Installable = $false
                }
            }
        }
    }

    return $null
}

function Get-RootMsrv {
    $manifestPath = Join-Path $repoRoot 'Cargo.toml'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "anvil: Cargo.toml not found at repository root '$repoRoot'"
    }

    $values = @{}
    $section = ''
    foreach ($line in (Get-Content -LiteralPath $manifestPath)) {
        if ($line -match '^\s*\[\s*([^\]]+)\s*\]\s*(?:#.*)?$') {
            $section = $Matches[1].Trim()
            continue
        }
        if ($section -in @('workspace.package', 'package') -and
            $line -match '^\s*["'']?rust-version["'']?\s*=\s*(["''])([^"'']+)\1\s*(?:#.*)?$') {
            $values[$section] = $Matches[2]
        }
    }

    if ($values.ContainsKey('workspace.package')) {
        return $values['workspace.package']
    }
    if ($values.ContainsKey('package')) {
        return $values['package']
    }

    throw 'anvil: no selecting rust-toolchain(.toml) and no root [workspace.package] or [package] rust-version; declare an MSRV or select a toolchain explicitly'
}

function Assert-UniformWorkspaceMsrv {
    $manifestPath = Join-Path $repoRoot 'Cargo.toml'
    $metadataText = (& cargo metadata --manifest-path $manifestPath --format-version 1 --no-deps 2>&1 | Out-String)
    if ($LASTEXITCODE -ne 0) {
        throw "anvil: cargo metadata failed while validating workspace MSRVs:`n$metadataText"
    }
    $metadata = $metadataText | ConvertFrom-Json
    $memberIds = [Collections.Generic.HashSet[string]]::new(
        [string[]] $metadata.workspace_members,
        [StringComparer]::Ordinal
    )
    $members = @($metadata.packages | Where-Object { $memberIds.Contains([string] $_.id) })
    $missing = @($members | Where-Object { [string]::IsNullOrWhiteSpace([string] $_.rust_version) } | ForEach-Object name)
    if ($missing.Count -gt 0) {
        throw "anvil: workspace packages without a resolved rust-version: $($missing -join ', '); declare one or select a toolchain explicitly"
    }

    $versions = @($members | ForEach-Object { [string] $_.rust_version } | Sort-Object -Unique)
    $rootMsrv = Get-RootMsrv
    if ($versions.Count -ne 1 -or $versions[0] -ne $rootMsrv) {
        throw "anvil: workspace packages must resolve to the root MSRV $rootMsrv; found $($versions -join ', '); select one catalog toolchain explicitly with rust-toolchain.toml"
    }
}

$fileSelection = Get-SelectingToolchainFile
if ($ValidateWorkspaceMsrv) {
    $skipWorkspaceMsrvValidation = if ([string]::IsNullOrWhiteSpace($env:ANVIL_STABLE_TOOLCHAIN_SOURCE)) {
        -not [string]::IsNullOrWhiteSpace($env:RUSTUP_TOOLCHAIN)
    } else {
        $env:ANVIL_STABLE_TOOLCHAIN_SOURCE -in @('environment', 'container')
    }
    if (-not $skipWorkspaceMsrvValidation -and $null -eq $fileSelection) {
        Assert-UniformWorkspaceMsrv
    }
    exit 0
}

$selection = if (-not [string]::IsNullOrWhiteSpace($env:RUSTUP_TOOLCHAIN)) {
    [pscustomobject]@{ Value = $env:RUSTUP_TOOLCHAIN; Source = 'environment'; Installable = $false }
} elseif ($null -ne $fileSelection) {
    $fileSelection
} else {
    [pscustomobject]@{ Value = Get-RootMsrv; Source = 'msrv'; Installable = $true }
}

if ($InstallIfMissing) {
    if (-not $selection.Installable) {
        exit 0
    }

    $installed = rustup toolchain list
    if ($LASTEXITCODE -ne 0) {
        throw 'anvil: rustup toolchain list failed'
    }
    if ($installed -match "(?m)^$([regex]::Escape($selection.Value))(?:-|$)") {
        exit 0
    }

    Write-Host "anvil: installing stable toolchain '$($selection.Value)'"
    rustup toolchain install $selection.Value --profile minimal
    if ($LASTEXITCODE -ne 0) {
        throw "anvil: failed to install stable toolchain '$($selection.Value)'"
    }
    exit 0
}

if ($ForEnvironment -and $selection.Source -eq 'file') {
    ''
} else {
    $selection.Value
}
exit 0
