# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.

param(
    [switch] $ValidateWorkspaceMsrv,
    [switch] $InstallIfMissing,
    [switch] $ForEnvironment,
    [switch] $MsrvToolchain,
    [switch] $InstallMsrvIfNeeded,
    [switch] $EmitToolchainFileOptions,
    [switch] $ApplyToolchainFileOptions
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3

$repoRoot = Split-Path -Parent $PSScriptRoot

function Get-RootToolchainFilePath {
    foreach ($name in @('rust-toolchain', 'rust-toolchain.toml')) {
        $path = Join-Path $repoRoot $name
        if (Test-Path -LiteralPath $path -PathType Leaf) {
            return $path
        }
    }
    return $null
}

function Read-RootToolchainFile([string] $path) {
    $content = Get-Content -LiteralPath $path -Raw
    if ([string]::IsNullOrWhiteSpace($content)) {
        throw "anvil: root toolchain file '$path' is empty; remove it or declare a toolchain configuration"
    }
    return $content
}

function Get-SelectingToolchainFile {
    $path = Get-RootToolchainFilePath
    if ($null -eq $path) {
        return $null
    }

    $content = Read-RootToolchainFile $path
    if ((Split-Path -Leaf $path) -eq 'rust-toolchain' -and $content.TrimStart() -notmatch '^\[') {
        return [pscustomobject]@{
            Path = $path
            Value = $content.Trim()
            Selector = 'channel'
            Source = 'file'
            Installable = $false
        }
    }

    $inToolchain = $false
    foreach ($line in $content -split '\r?\n') {
        if ($line -match '^\s*\[\s*toolchain\s*\]\s*(?:#.*)?$') {
            $inToolchain = $true
            continue
        }
        if ($line -match '^\s*\[') {
            $inToolchain = $false
            continue
        }
        if ($inToolchain -and $line -match '^\s*["'']?(channel|path)["'']?\s*=\s*(["''])([^"'']+)\2\s*(?:#.*)?$') {
            $value = $Matches[3]
            if ($Matches[1] -eq 'path' -and -not [IO.Path]::IsPathRooted($value)) {
                $value = [IO.Path]::GetFullPath((Join-Path $repoRoot $value))
            }
            return [pscustomobject]@{
                Path = $path
                Value = $value
                Selector = $Matches[1]
                Source = 'file'
                Installable = $false
            }
        }
    }
    return $null
}

function Get-ToolchainFileOptions {
    $path = Get-RootToolchainFilePath
    if ($null -eq $path) {
        return $null
    }

    $content = Read-RootToolchainFile $path
    $section = [regex]::Match(
        $content,
        '(?ms)^\s*\[\s*toolchain\s*\]\s*(?:#.*)?$(.*?)(?=^\s*\[|\z)'
    )
    if (-not $section.Success) {
        return $null
    }

    $body = $section.Groups[1].Value
    $profileMatch = [regex]::Match(
        $body,
        '(?m)^\s*["'']?profile["'']?\s*=\s*(["''])([^"'']+)\1\s*(?:#.*)?$'
    )
    $readArray = {
        param([string] $name)
        $arrayMatch = [regex]::Match(
            $body,
            "(?ms)^\s*[`"']?$name[`"']?\s*=\s*\[(.*?)\]"
        )
        if (-not $arrayMatch.Success) {
            return @()
        }
        return @(
            [regex]::Matches($arrayMatch.Groups[1].Value, '(["''])([^"'']+)\1') |
                ForEach-Object { $_.Groups[2].Value }
        )
    }

    return [pscustomobject]@{
        Path = $path
        Profile = if ($profileMatch.Success) { $profileMatch.Groups[2].Value } else { $null }
        Components = @(& $readArray 'components')
        Targets = @(& $readArray 'targets')
    }
}

function Get-RootMsrv([switch] $AllowMissing) {
    $manifestPath = Join-Path $repoRoot 'Cargo.toml'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "anvil: Cargo.toml not found at repository root '$repoRoot'"
    }

    $values = @{}
    $section = ''
    foreach ($line in (Get-Content -LiteralPath $manifestPath)) {
        if ($line -match '^\s*\[\s*([^\]]+)\s*\]\s*(?:#.*)?$') {
            $section = $Matches[1].Trim()
            continue
        }
        if ($section -in @('workspace.package', 'package') -and
            $line -match '^\s*["'']?rust-version["'']?\s*=\s*(["''])([^"'']+)\1\s*(?:#.*)?$') {
            $values[$section] = $Matches[2]
        }
    }

    if ($values.ContainsKey('workspace.package')) {
        return $values['workspace.package']
    }
    if ($values.ContainsKey('package')) {
        return $values['package']
    }

    if ($AllowMissing) {
        return $null
    }
    throw 'anvil: no selecting rust-toolchain(.toml) and no root [workspace.package] or [package] rust-version; declare an MSRV or select a toolchain explicitly'
}

function Assert-UniformWorkspaceMsrv {
    $manifestPath = Join-Path $repoRoot 'Cargo.toml'
    $metadataText = (& cargo metadata --manifest-path $manifestPath --format-version 1 --no-deps 2>&1 | Out-String)
    if ($LASTEXITCODE -ne 0) {
        throw "anvil: cargo metadata failed while validating workspace MSRVs:`n$metadataText"
    }
    $metadata = $metadataText | ConvertFrom-Json
    $memberIds = [Collections.Generic.HashSet[string]]::new(
        [string[]] $metadata.workspace_members,
        [StringComparer]::Ordinal
    )
    $members = @($metadata.packages | Where-Object { $memberIds.Contains([string] $_.id) })
    $missing = @($members | Where-Object { [string]::IsNullOrWhiteSpace([string] $_.rust_version) } | ForEach-Object name)
    if ($missing.Count -gt 0) {
        throw "anvil: workspace packages without a resolved rust-version: $($missing -join ', '); declare one or select a toolchain explicitly"
    }

    $versions = @($members | ForEach-Object { [string] $_.rust_version } | Sort-Object -Unique)
    $rootMsrv = Get-RootMsrv
    if ($versions.Count -ne 1 -or $versions[0] -ne $rootMsrv) {
        throw "anvil: workspace packages must resolve to the root MSRV $rootMsrv; found $($versions -join ', '); select one catalog toolchain explicitly with rust-toolchain.toml"
    }
}

function Get-MsrvSelection {
    $msrv = Get-RootMsrv -AllowMissing
    if ([string]::IsNullOrWhiteSpace($msrv)) {
        return $null
    }

    if (-not [string]::IsNullOrWhiteSpace($env:ANVIL_MSRV_TOOLCHAIN)) {
        return [pscustomobject]@{
            Value = $env:ANVIL_MSRV_TOOLCHAIN
            Source = 'mapped-msrv'
            Installable = $false
            Mapped = $true
        }
    }
    return [pscustomobject]@{ Value = $msrv; Source = 'msrv'; Installable = $true; Mapped = $false }
}

function Apply-ToolchainFileOptions([object] $toolchain) {
    if ($toolchain.Source -eq 'file' -or $null -eq $toolchainFileOptions) {
        return
    }
    foreach ($component in $toolchainFileOptions.Components) {
        rustup component add --toolchain $toolchain.Value $component
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "anvil: toolchain-file component '$component' is unavailable for '$($toolchain.Value)'; rustup would skip an unavailable file component"
        }
    }
    foreach ($target in $toolchainFileOptions.Targets) {
        rustup target add --toolchain $toolchain.Value $target
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "anvil: toolchain-file target '$target' is unavailable for '$($toolchain.Value)'; rustup would skip an unavailable file target"
        }
    }
}

function Install-Toolchain([object] $toolchain, [string] $label) {
    if ($toolchain.Installable) {
        $installed = rustup toolchain list
        if ($LASTEXITCODE -ne 0) {
            throw 'anvil: rustup toolchain list failed'
        }
        if ($installed -notmatch "(?m)^$([regex]::Escape($toolchain.Value))(?:-|$)") {
            $profile = if ($null -ne $toolchainFileOptions -and $toolchainFileOptions.Profile) {
                $toolchainFileOptions.Profile
            } else {
                'minimal'
            }
            Write-Host "anvil: installing $label toolchain '$($toolchain.Value)'"
            rustup toolchain install $toolchain.Value --profile $profile
            if ($LASTEXITCODE -ne 0) {
                throw "anvil: failed to install $label toolchain '$($toolchain.Value)'"
            }
        }
    }
    Apply-ToolchainFileOptions $toolchain
}

$fileSelection = Get-SelectingToolchainFile
$toolchainFileOptions = Get-ToolchainFileOptions
if ($EmitToolchainFileOptions) {
    if ($null -ne $toolchainFileOptions) {
        $toolchainFileOptions | ConvertTo-Json -Compress
    }
    exit 0
}
if ($ValidateWorkspaceMsrv) {
    $skipWorkspaceMsrvValidation = -not [string]::IsNullOrWhiteSpace($env:RUSTUP_TOOLCHAIN)
    if (-not $skipWorkspaceMsrvValidation -and $null -eq $fileSelection) {
        Assert-UniformWorkspaceMsrv
    }
    exit 0
}

if ($MsrvToolchain -or $InstallMsrvIfNeeded) {
    $msrvSelection = Get-MsrvSelection
    if ($null -eq $msrvSelection) {
        exit 0
    }
    if ($InstallMsrvIfNeeded) {
        if ($msrvSelection.Mapped) {
            & cargo "+$($msrvSelection.Value)" --version *> $null
            if ($LASTEXITCODE -ne 0) {
                throw "anvil: mapped MSRV toolchain '$($msrvSelection.Value)' is unavailable; provision ANVIL_MSRV_TOOLCHAIN or unset it to let Anvil install the declared public MSRV"
            }
        }
        Install-Toolchain $msrvSelection 'MSRV'
    } else {
        $msrvSelection.Value
    }
    exit 0
}

$selection = if (-not [string]::IsNullOrWhiteSpace($env:RUSTUP_TOOLCHAIN)) {
    [pscustomobject]@{ Value = $env:RUSTUP_TOOLCHAIN; Source = 'environment'; Installable = $false }
} elseif ($null -ne $fileSelection) {
    $fileSelection
} else {
    [pscustomobject]@{ Value = Get-RootMsrv; Source = 'msrv'; Installable = $true }
}

if ($ApplyToolchainFileOptions) {
    Apply-ToolchainFileOptions $selection
    exit 0
}

if ($InstallIfMissing) {
    Install-Toolchain $selection 'stable'
    exit 0
}

if ($ForEnvironment -and $selection.Source -eq 'file') {
    ''
} else {
    $selection.Value
}
exit 0
